"""
HLC Autoresearch — Corpus Builder
===================================
Generates a diverse, representative corpus of English text samples
for optimizing and validating the HLC compression system.

100 samples across 10 categories, split 80/20 train/holdout.
"""

import json
import random
from pathlib import Path

random.seed(42)  # reproducible splits

# ═══════════════════════════════════════════════════════════
# CORPUS — 100 diverse English text samples
# 10 categories × 10 samples each
# ═══════════════════════════════════════════════════════════

CORPUS = []

# ── Category 1: Technical Discussion (10) ──
CORPUS.extend([
    {"category": "technical", "text": "Absolutely, and this is the part that deserves more attention. The compaction quality is bounded by the compacting model's ability to understand what matters. A more capable model will produce better summaries because it can reason about relevance, identify dependencies between statements, and recognize which details are structural versus decorative. But even the best model is guessing about future relevance — it doesn't know what you'll ask next."},
    {"category": "technical", "text": "The main bottleneck in the current architecture is the database connection pooling layer. When we run more than fifty concurrent requests, the pool exhausts and new connections have to wait. I think we should consider switching to a connection-per-request model with short-lived connections, or alternatively increase the pool size and add circuit breakers to prevent cascading failures."},
    {"category": "technical", "text": "We need to rethink how the caching layer interacts with the authentication service. Right now, every request hits the auth server even if the token was validated five seconds ago. A simple TTL cache with a sixty-second window would reduce auth server load by about eighty percent without meaningfully increasing security risk. The tradeoff is that token revocations would take up to a minute to propagate."},
    {"category": "technical", "text": "The transformer architecture relies on self-attention mechanisms that allow the model to weigh the importance of different parts of the input sequence. Each attention head learns to focus on different types of relationships between tokens. The multi-head attention mechanism enables the model to attend to information from different representation subspaces at different positions simultaneously."},
    {"category": "technical", "text": "I've been looking at the memory usage patterns and I think the problem is that we're holding too many objects in the session cache. The garbage collector can't free them because they're still referenced through the event listener chain. If we switch to weak references for the event bindings, the objects should become eligible for collection once the primary reference is dropped."},
    {"category": "technical", "text": "The API rate limiting strategy needs to account for burst traffic patterns. A simple token bucket algorithm would work well here because it allows short bursts while maintaining an average rate over time. We should set the bucket size to handle about three times the normal request rate and refill at the steady-state rate. This gives clients room to send clustered requests without hitting limits."},
    {"category": "technical", "text": "One thing I noticed about the deployment pipeline is that the integration tests are running sequentially instead of in parallel. This adds about twenty minutes to every deploy cycle. If we containerize each test suite and run them concurrently on separate instances, we could cut the total test time down to about five minutes. The cost would be minimal since we only spin up the instances during deployments."},
    {"category": "technical", "text": "The search indexing service is falling behind during peak hours. The root cause is that we're reindexing the entire document on every update, even for small changes like metadata modifications. An incremental indexing approach that only updates the changed fields would reduce indexing time by an order of magnitude for most updates and allow the service to keep up with the write volume."},
    {"category": "technical", "text": "We should consider implementing a feature flag system before the next major release. This would allow us to deploy new features to production behind flags and gradually roll them out to increasing percentages of users. If something goes wrong, we can disable the feature instantly without a full rollback. The implementation is straightforward and the risk reduction is significant."},
    {"category": "technical", "text": "The data pipeline currently processes records in batch mode every fifteen minutes. For the real-time dashboard to work properly, we need to switch to a streaming architecture. I propose using a message queue to capture events as they happen, with a stream processor that aggregates metrics in sliding windows. The batch pipeline would continue to run for historical backfills and reconciliation."},
])

# ── Category 2: Casual Conversation (10) ──
CORPUS.extend([
    {"category": "casual", "text": "Hey, how are you doing today? I was thinking about what you said yesterday about the project. I don't think we should rush it because there are still a lot of things we need to figure out. Let me know what you think and we can talk about it more later. By the way, did you see the new update? It's pretty cool but I'm not sure if it fixes the problem we were having."},
    {"category": "casual", "text": "I just got back from the grocery store and they were completely out of everything I needed. I had to go to three different stores to find all the ingredients for dinner tonight. I'm making that pasta recipe you told me about last week. Hopefully it turns out okay because I've never made it before and the instructions seem kind of complicated."},
    {"category": "casual", "text": "Did you end up going to that concert last weekend? I heard the venue was packed and the band played for almost three hours. I was going to go but something came up at the last minute and I couldn't make it. I'm still pretty bummed about it because they don't come to town very often and I've been wanting to see them for a long time."},
    {"category": "casual", "text": "So I finally finished that book you recommended and I have to say it was really good. The ending caught me completely off guard. I didn't see that twist coming at all. Have you read anything else by the same author? I'd love to find something similar because I'm looking for a new book to start and I trust your taste."},
    {"category": "casual", "text": "My neighbor just got a new puppy and it's the cutest thing ever. It keeps escaping from their yard and ending up in ours. I don't mind at all because it's so friendly and loves to play. I've been thinking about getting a dog myself but I'm not sure I have the time to take care of one properly right now."},
    {"category": "casual", "text": "I can't believe it's already March. This year is flying by so fast. It feels like New Year's was just last week. I still haven't done half the things I planned to do this year. I really need to start being more intentional about how I spend my time instead of just letting the days go by."},
    {"category": "casual", "text": "Have you tried that new coffee shop on the corner? I went there yesterday morning and it was really nice. The coffee is great and they have this amazing pastry selection. It's a bit more expensive than the usual place but I think it's worth it for the quality. We should go together sometime this week if you're free."},
    {"category": "casual", "text": "I'm thinking about learning to play the guitar. I know it's going to take a lot of practice but I've always wanted to learn and I figure now is as good a time as any. Do you know anyone who gives lessons? I'd rather learn from a person than just watch tutorials online because I think I'd stay more motivated that way."},
    {"category": "casual", "text": "The weather has been so weird lately. One day it's warm and sunny and the next day it's freezing cold and raining. I never know what to wear when I leave the house. I've started keeping a jacket in my car just in case because I've been caught in the rain too many times this month already."},
    {"category": "casual", "text": "I watched this really interesting documentary last night about how food companies design their products to be as addictive as possible. It was kind of disturbing but also really fascinating. They spend millions of dollars on research to find the perfect combination of salt, sugar, and fat that makes you want to keep eating. It made me think twice about what I've been buying."},
])

# ── Category 3: Business / Professional (10) ──
CORPUS.extend([
    {"category": "business", "text": "Thank you for your prompt response regarding the quarterly report. I have reviewed the financial projections and would like to schedule a meeting to discuss the budget allocation for the upcoming fiscal year. In addition to the revenue forecasts, we should also consider the operational expenses and potential cost reduction strategies. Please let me know your availability for next week. I would appreciate it if you could also prepare a brief summary of the key performance indicators for the board presentation."},
    {"category": "business", "text": "Following up on our conversation from last week, I wanted to confirm that the contract revision has been sent to the legal team for review. They have indicated that they should be able to complete their assessment by the end of this week. Once we have their feedback, I will schedule a call with all stakeholders to discuss any necessary modifications before we proceed with the final signing."},
    {"category": "business", "text": "I am writing to inform you that the product launch timeline has been adjusted. Due to unexpected delays in the supply chain, we have decided to push the release date back by approximately three weeks. The marketing team has been notified and is updating all promotional materials accordingly. We believe this additional time will allow us to ensure the highest quality standards are met before going to market."},
    {"category": "business", "text": "Please find attached the revised proposal for the consulting engagement. We have incorporated all of the feedback from the preliminary review meeting and adjusted the scope to better align with your stated objectives. The total project cost has been updated to reflect the changes in deliverables. I would be happy to walk you through the modifications in a brief call at your convenience."},
    {"category": "business", "text": "The quarterly performance review indicates that our customer retention rate has improved by twelve percent compared to the same period last year. This improvement can be attributed to several factors, including the new onboarding process, enhanced customer support response times, and the loyalty program that was introduced in January. I recommend that we continue to invest in these areas to maintain this positive trajectory."},
    {"category": "business", "text": "I wanted to bring to your attention a potential issue with the vendor agreement that is set to renew next month. The current terms include an automatic price increase of eight percent annually, which I believe is above market rate for comparable services. I suggest we initiate renegotiation discussions before the renewal date to explore more favorable pricing or consider alternative vendors."},
    {"category": "business", "text": "As discussed in the leadership meeting, we are implementing a new project management framework across all departments. The transition will begin next quarter and will be rolled out in phases. Training sessions for team leads will be conducted during the first two weeks, followed by department-wide adoption. Please ensure that your team members are aware of the upcoming changes and encourage them to participate in the training."},
    {"category": "business", "text": "The market analysis report for the Southeast Asian expansion has been completed. Our findings suggest that the region presents significant growth opportunities, particularly in the technology and financial services sectors. However, there are regulatory considerations that will require careful navigation. I have prepared a detailed risk assessment that I would like to present at the next strategy meeting."},
    {"category": "business", "text": "I am pleased to announce that our team has successfully completed the system migration ahead of schedule. The new platform is now fully operational and all data has been transferred without any loss or corruption. Initial performance metrics indicate a thirty percent improvement in processing speed. I would like to thank everyone involved for their dedication and hard work throughout this complex transition."},
    {"category": "business", "text": "We need to discuss the staffing plan for the upcoming project. Based on the current timeline and scope of work, I estimate that we will need to bring on three additional developers and one project manager. I have already begun reviewing candidates from our preferred recruitment partners and would like to present the shortlist for your approval by the end of this week."},
])

# ── Category 4: Technical Documentation (10) ──
CORPUS.extend([
    {"category": "documentation", "text": "The system architecture consists of three primary components: the ingestion pipeline, the processing engine, and the storage layer. The ingestion pipeline handles incoming data from multiple sources including REST APIs, message queues, and batch file uploads. Data is validated, transformed, and normalized before being passed to the processing engine. The processing engine applies business logic, performs aggregations, and generates derived metrics. Results are persisted to the storage layer which supports both real-time queries and historical analysis through a combination of time-series databases and columnar data warehouses."},
    {"category": "documentation", "text": "To configure the authentication module, update the settings file with your identity provider credentials. The module supports OAuth 2.0, SAML, and OpenID Connect protocols. Token refresh is handled automatically by the middleware, which checks the expiration time on each request and renews the token if it will expire within the next five minutes. Failed authentication attempts are logged and can trigger account lockout after a configurable number of retries."},
    {"category": "documentation", "text": "The logging framework provides three levels of output: debug, info, and error. Debug logs include detailed execution traces and are intended for development use only. Info logs capture significant events such as user actions, system state changes, and performance metrics. Error logs record unexpected failures and include stack traces for debugging. Log output can be directed to the console, a file, or an external logging service."},
    {"category": "documentation", "text": "The database schema consists of five core tables that form the foundation of the application. The users table stores account information and authentication credentials. The projects table contains project metadata and configuration settings. The tasks table tracks individual work items and their current status. The comments table stores threaded discussions associated with tasks. The activity table provides an audit trail of all changes made to any entity in the system."},
    {"category": "documentation", "text": "The deployment process follows a blue-green strategy to minimize downtime during releases. The current production environment runs on the blue stack while the new version is deployed to the green stack. After deployment, automated health checks verify that the green stack is functioning correctly. Once verified, traffic is gradually shifted from blue to green over a period of thirty minutes. The blue stack remains available for rapid rollback if any issues are detected."},
    {"category": "documentation", "text": "The notification service supports multiple delivery channels including email, push notifications, and in-app messages. Each notification type is defined by a template that specifies the content, formatting, and delivery rules. Users can configure their notification preferences to control which channels are used for each notification type. The service implements a priority queue to ensure that critical notifications are delivered promptly even under high load conditions."},
    {"category": "documentation", "text": "The backup system performs automated snapshots of all production databases every six hours. Snapshots are stored in a geographically distributed storage system with copies maintained in at least three different regions. Retention policy keeps hourly snapshots for the past week, daily snapshots for the past month, and weekly snapshots for the past year. Point-in-time recovery is available for the most recent seven days of data."},
    {"category": "documentation", "text": "The file upload module accepts documents up to fifty megabytes in size. Supported formats include PDF, DOCX, XLSX, and common image formats. Files are scanned for malware before being stored in the content delivery network. Each uploaded file receives a unique identifier that can be used to retrieve it through the API. Access control is enforced at the file level, allowing granular permissions to be set for individual users or groups."},
    {"category": "documentation", "text": "The monitoring dashboard displays real-time metrics for all production services. Key indicators include request latency, error rate, throughput, and resource utilization. Alert thresholds can be configured for each metric, with notifications sent to the on-call team when thresholds are exceeded. Historical data is available for trend analysis and capacity planning. The dashboard also provides a service dependency map that visualizes the relationships between components."},
    {"category": "documentation", "text": "The reporting module generates scheduled and on-demand reports from the data warehouse. Reports can be customized using a template system that supports dynamic filtering, grouping, and aggregation. Output formats include PDF, CSV, and interactive web dashboards. Scheduled reports are delivered via email or saved to a shared drive. The module includes a query optimizer that caches frequently accessed data sets to reduce report generation time."},
])

# ── Category 5: Creative / Narrative (10) ──
CORPUS.extend([
    {"category": "creative", "text": "The old lighthouse keeper stood at the edge of the cliff, watching the storm clouds gather on the horizon. He had seen countless storms in his forty years at this post, but something about this one felt different. The air was heavy with electricity, and the seabirds had fallen silent hours ago. He checked the lamp one more time, making sure the mechanism was properly oiled and the lens was spotless. Tonight would be a long night, and the ships out there would need every bit of light he could give them."},
    {"category": "creative", "text": "She found the letter tucked inside a book at the secondhand shop. The paper was yellowed and the ink had faded to a pale blue, but the handwriting was still legible. It was a love letter, written by someone named Thomas to someone named Eleanor, dated June of nineteen forty-three. She read it three times standing in the aisle, tears forming in her eyes at the tenderness of the words, wondering what had become of them and whether they had found their way back to each other."},
    {"category": "creative", "text": "The garden had been her mother's pride and joy for as long as anyone could remember. Every spring without fail, the roses would bloom in waves of red and pink and white, filling the yard with a perfume so thick you could almost taste it. Now, six months after the funeral, the roses were growing wild, climbing over the fence and tangling with the neighbor's ivy. She knew she should trim them back, but there was something beautiful about their refusal to be contained."},
    {"category": "creative", "text": "The city looked different from up here. From the observation deck, the streets that felt so crowded and chaotic at ground level were reduced to neat geometric patterns. The cars moved like blood cells through arteries, the pedestrians like tiny purposeful ants. He pressed his forehead against the cold glass and wondered how many of those tiny figures were having the worst day of their lives right now, and how many were having the best."},
    {"category": "creative", "text": "They had been walking for three days when they finally reached the river. The map showed a bridge, but what they found was a handful of rotting wooden planks spanning a gap of thirty feet over fast-moving water. The guide tested the first plank with his boot, nodded once, and started across without looking back. One by one, they followed, each step a negotiation between fear and the knowledge that there was no other way forward."},
    {"category": "creative", "text": "The piano had sat in the corner of the living room for twelve years, untouched since the day his daughter left for college. He had meant to sell it or donate it, but somehow it always stayed, gathering dust and serving as a shelf for mail and keys. One evening, on a whim, he lifted the lid and pressed a single key. The note rang out clear and true, filling the empty house with a sound that made him sit down on the bench and play for the first time in over a decade."},
    {"category": "creative", "text": "Morning came slowly to the fishing village, a gradual lightening of gray rather than any dramatic sunrise. The boats had already gone out, their lanterns bobbing in the pre-dawn darkness like earthbound stars. She watched from the kitchen window while the kettle heated, counting the lights and matching them to names. Her husband's boat was the third from the left, and she tracked its movement until it disappeared around the headland."},
    {"category": "creative", "text": "The market was a sensory overload in the best possible way. Stalls overflowed with pyramids of spices in every shade of gold and brown and red, their aromas mixing in the warm air until it was impossible to isolate any single scent. Vendors called out prices in a musical cadence that turned commerce into performance. She moved through the narrow aisles slowly, letting herself be carried by the flow of the crowd rather than fighting against it."},
    {"category": "creative", "text": "He kept the photograph in his wallet, folded twice and worn soft at the creases. It showed four boys on a beach, squinting into the sun, their arms thrown around each other's shoulders in that easy way that only exists in childhood. He was the one on the left, grinning so wide his eyes were nearly shut. The others had scattered across the country and then the world, but in this picture they were still together, still young, still certain that summer would never end."},
    {"category": "creative", "text": "The train pulled out of the station at exactly half past seven, just as the conductor had promised. She pressed her face to the window and watched the city slide away, the buildings growing shorter and further apart until they gave way to open fields. There was something liberating about leaving, even temporarily. Every mile of track between her and home felt like a weight being lifted. By the time the countryside turned to rolling hills, she was already breathing easier."},
])

# ── Category 6: Academic / Research (10) ──
CORPUS.extend([
    {"category": "academic", "text": "We present a novel approach to context window optimization in large language models through hierarchical lexical compression. Our method achieves significant token reduction without information loss by applying deterministic rule-based transformations at multiple levels of linguistic granularity. Unlike semantic compression approaches which require model inference and produce irreversible information loss, our system operates through precomputed codebook substitutions that preserve all original content."},
    {"category": "academic", "text": "Recent advances in neural architecture search have demonstrated that automated methods can discover model configurations that outperform hand-designed architectures on standard benchmarks. However, the computational cost of these search procedures remains prohibitive for most research groups. Our work introduces an efficient proxy task that reduces search time by two orders of magnitude while maintaining a strong correlation with full-scale performance."},
    {"category": "academic", "text": "The relationship between model scale and emergent capabilities has been a central topic in recent language model research. Several studies have shown that certain abilities appear to emerge discontinuously as models cross specific parameter thresholds. However, the mechanisms underlying these phase transitions remain poorly understood. We propose a theoretical framework that explains emergence as a consequence of representational capacity interacting with task complexity."},
    {"category": "academic", "text": "Our experimental results demonstrate that the proposed method achieves state-of-the-art performance on four out of five benchmark datasets. The improvement is particularly pronounced on tasks requiring long-range dependency modeling, where our architecture outperforms the baseline by a margin of twelve percent. We attribute this improvement to the novel attention mechanism that allows the model to maintain coherent representations across extended sequence lengths."},
    {"category": "academic", "text": "The ethical implications of deploying autonomous decision-making systems in healthcare settings have generated significant debate in the research community. While these systems have shown promising results in diagnostic accuracy, concerns remain about accountability, transparency, and the potential for algorithmic bias to exacerbate existing health disparities. A comprehensive regulatory framework is needed to balance innovation with patient safety."},
    {"category": "academic", "text": "We conducted a systematic review of published literature on transfer learning techniques applied to low-resource language processing. Our analysis encompassed one hundred and forty-seven papers published between two thousand and eighteen and two thousand and twenty-five. The findings indicate that multilingual pretraining followed by task-specific fine-tuning consistently outperforms other approaches, though the magnitude of improvement varies significantly across language families."},
    {"category": "academic", "text": "The proposed optimization algorithm converges to a local minimum in polynomial time under standard assumptions about the loss landscape. We provide theoretical guarantees on the convergence rate and demonstrate empirically that the algorithm finds solutions of comparable quality to existing methods while requiring significantly fewer gradient evaluations. This efficiency gain makes the approach particularly suitable for resource-constrained training environments."},
    {"category": "academic", "text": "Data augmentation strategies have proven effective in improving model robustness and generalization performance. Our study evaluates seven commonly used augmentation techniques across three distinct task categories and finds that the optimal strategy is highly task-dependent. We propose an adaptive selection mechanism that dynamically chooses the most appropriate augmentation method based on training dynamics observed during the initial epochs."},
    {"category": "academic", "text": "The interpretability of deep neural networks remains an open challenge in the field. While attention weights are frequently cited as providing insight into model behavior, recent work has questioned whether attention distributions faithfully represent the underlying decision process. Our analysis provides evidence that attention patterns are necessary but not sufficient for understanding model predictions, and we introduce complementary diagnostic tools."},
    {"category": "academic", "text": "Climate modeling simulations require enormous computational resources that limit the resolution and scope of projections. We present a machine learning approach that emulates the behavior of high-resolution physics-based models at a fraction of the computational cost. The emulator is trained on historical simulation outputs and produces predictions that closely match the reference model while enabling rapid exploration of scenario parameters."},
])

# ── Category 7: Customer Support (10) ──
CORPUS.extend([
    {"category": "support", "text": "I understand your frustration with the billing issue. Let me look into this for you right away. It appears that the charge was applied twice due to a processing error on our end. I have initiated a refund for the duplicate charge, which should appear in your account within three to five business days. Is there anything else I can help you with today? If you experience any further issues, please don't hesitate to contact us again. We value your business and want to make sure this is resolved to your satisfaction."},
    {"category": "support", "text": "Thank you for reaching out about the delivery delay. I can see that your order was shipped on schedule but appears to have been held at the regional distribution center. This sometimes happens during periods of high volume. I have contacted the carrier to expedite the delivery and you should receive an updated tracking notification within the next few hours. I sincerely apologize for the inconvenience."},
    {"category": "support", "text": "I appreciate you bringing this to our attention. The feature you're describing was recently updated and the interface has changed slightly from what you may be used to. Let me walk you through the new process step by step. First, navigate to the settings menu and select the integrations tab. From there, you should see a new option that allows you to configure the connection. If you run into any trouble along the way, I'm happy to stay on and guide you through it."},
    {"category": "support", "text": "I'm sorry to hear that the product didn't meet your expectations. We stand behind the quality of everything we sell and I'd like to make this right for you. You have two options: I can issue a full refund to your original payment method, or I can send a replacement at no additional cost. Which would you prefer? Either way, you don't need to return the current item. Just let me know how you'd like to proceed."},
    {"category": "support", "text": "Thank you for your patience while I looked into this. I've reviewed your account history and it appears that the subscription change you requested last month was not processed correctly. I have manually applied the correct plan and adjusted the billing to reflect the rate you were originally quoted. You will see a credit on your next statement for the difference. I apologize for the error and any confusion it may have caused."},
    {"category": "support", "text": "I understand that you're having trouble accessing your account. For security purposes, I'll need to verify your identity before I can make any changes. Could you please confirm the email address associated with the account and the last four digits of the payment method on file? Once I've verified your identity, I can reset the password and send you a new login link right away."},
    {"category": "support", "text": "Great question about the compatibility. The software is designed to work with most operating systems released in the past five years. However, there are a few known issues with older versions that our engineering team is currently working to resolve. I'd recommend checking the system requirements page on our website for the most up-to-date compatibility information. If your system isn't currently supported, I can add you to the notification list so you'll be alerted when support is added."},
    {"category": "support", "text": "I can see that you've been a loyal customer for over three years and I really appreciate your continued business. Based on your account history, I'd like to offer you a complimentary upgrade to our premium tier for the next three months. This will give you access to all the advanced features at no extra cost. If you enjoy the premium experience and decide to keep it, I can also arrange a discounted rate for you as a thank you for your loyalty."},
    {"category": "support", "text": "The error message you're seeing typically indicates a conflict with the browser cache. The quickest fix is to clear your browser cache and cookies, then try again. If that doesn't resolve the issue, try opening the application in a private browsing window. This helps us determine whether the problem is related to stored data or something else. If neither of those steps works, please let me know and I'll escalate this to our technical team for further investigation."},
    {"category": "support", "text": "I want to make sure I understand your concern correctly. You placed an order for two items but only received one, and the packing slip shows both items as shipped. Is that right? Let me check the warehouse records to see what happened. It's possible that the second item was packed separately and is arriving in a different shipment. I'll have a definitive answer for you within the hour and will follow up with the details."},
])

# ── Category 8: Instructional / How-to (10) ──
CORPUS.extend([
    {"category": "instructional", "text": "To set up the development environment, first install the required dependencies using the package manager. Make sure you have the latest version of the runtime installed on your system. Next, clone the repository and navigate to the project directory. Create a virtual environment to isolate your project dependencies from the system packages. Activate the virtual environment and run the installation script. The configuration file should be updated with your specific settings before running the application for the first time."},
    {"category": "instructional", "text": "Before you begin painting, prepare the surface by sanding it lightly with fine-grit sandpaper. Wipe away any dust with a damp cloth and allow it to dry completely. Apply a thin coat of primer and let it cure for at least four hours. Once the primer is dry, apply the first coat of paint using long, even strokes in one direction. Allow the first coat to dry before applying the second. Two coats are usually sufficient for good coverage."},
    {"category": "instructional", "text": "To change the oil in your vehicle, start by running the engine for a few minutes to warm the oil. This makes it flow more easily. Position a drain pan beneath the oil plug and carefully remove the plug. Allow all the old oil to drain completely, which usually takes about ten minutes. Replace the drain plug and tighten it securely. Remove the old oil filter and install the new one. Finally, add the recommended amount of fresh oil and check the level with the dipstick."},
    {"category": "instructional", "text": "Creating a budget is one of the most important steps toward financial stability. Start by listing all of your sources of income for the month. Then list all of your fixed expenses such as rent, utilities, and insurance. Next, track your variable expenses like groceries, entertainment, and dining out. Subtract your total expenses from your total income to see how much you have left over. If the number is negative, look for areas where you can reduce spending."},
    {"category": "instructional", "text": "To make a basic sourdough starter, combine equal parts flour and water in a clean glass jar. Stir thoroughly until no dry flour remains. Cover loosely and let it sit at room temperature for twenty-four hours. Each day, discard half of the starter and feed it with fresh flour and water. After about five to seven days, you should notice bubbles forming and a pleasant sour smell. This indicates that the wild yeast has become active and the starter is ready to use."},
    {"category": "instructional", "text": "Setting up a home network begins with choosing the right location for your wireless router. Place it in a central location away from walls and metal objects. Connect the router to your modem using an ethernet cable and power it on. Access the router's configuration page through a web browser using the default address printed on the device. Change the default password immediately and set up a secure wireless network name and password using the strongest encryption available."},
    {"category": "instructional", "text": "To write an effective resume, start with a clear and concise summary statement that highlights your most relevant qualifications. List your work experience in reverse chronological order, focusing on accomplishments rather than duties. Use action verbs and quantify your achievements wherever possible. Include your education, relevant skills, and any certifications. Keep the format clean and consistent and limit the length to one or two pages depending on your experience level."},
    {"category": "instructional", "text": "Planting a vegetable garden requires careful planning. Choose a location that receives at least six hours of direct sunlight per day. Test the soil and amend it with compost if necessary to improve drainage and nutrient content. Plan your layout based on the spacing requirements of each plant and consider companion planting to maximize growth and minimize pests. Start seeds indoors about six weeks before the last frost date and transplant them outdoors when the soil temperature is consistently above sixty degrees."},
    {"category": "instructional", "text": "To properly perform CPR on an adult, first check that the scene is safe and call emergency services. Place the person on their back on a firm surface. Position the heel of one hand on the center of the chest between the nipples, place your other hand on top, and interlock your fingers. Push hard and fast at a rate of one hundred to one hundred and twenty compressions per minute, allowing the chest to fully recoil between compressions. Continue until help arrives."},
    {"category": "instructional", "text": "Learning to meditate begins with finding a quiet comfortable place where you won't be disturbed. Sit in a relaxed but upright position and close your eyes. Focus your attention on your breathing, noticing the sensation of air entering and leaving your body. When your mind wanders, and it will, gently bring your attention back to the breath without judgment. Start with just five minutes per day and gradually increase the duration as you become more comfortable with the practice."},
])

# ── Category 9: Email / Correspondence (10) ──
CORPUS.extend([
    {"category": "email", "text": "I hope this message finds you well. I wanted to follow up on the proposal we discussed during our meeting last Tuesday. After reviewing the numbers with my team, we believe the project is viable and would like to move forward with the next phase. Could we schedule a call this week to discuss the implementation timeline and resource requirements? I'm available Thursday afternoon or Friday morning."},
    {"category": "email", "text": "I'm writing to confirm your reservation for the annual company retreat. The event will be held at the lakeside conference center from June fifteenth through June seventeenth. Accommodation and meals are included. Please let us know if you have any dietary restrictions or special requirements by the end of this month so we can make the necessary arrangements. A detailed itinerary will be sent out two weeks before the event."},
    {"category": "email", "text": "Thank you for submitting your application for the senior developer position. We were impressed with your background and would like to invite you for an interview. The interview will consist of two parts: a technical assessment lasting approximately ninety minutes, followed by a conversation with the team lead and hiring manager. Please let me know your availability for next week and I will coordinate the schedule."},
    {"category": "email", "text": "I regret to inform you that the shipment you were expecting has been delayed due to unforeseen circumstances at the manufacturing facility. We are working diligently to resolve the issue and expect the order to be fulfilled within the next two weeks. As a gesture of goodwill, we would like to offer you free expedited shipping once the items are ready. Please accept our sincere apologies for any inconvenience this may cause."},
    {"category": "email", "text": "Just a quick note to say thank you for your help with the presentation yesterday. Your insights on the market trends were exactly what we needed and the client was visibly impressed. I've already received positive feedback from their team and they've asked us to prepare a more detailed analysis. I'll loop you in on the follow-up meeting once it's scheduled. Great work all around."},
    {"category": "email", "text": "I wanted to remind everyone that the deadline for submitting expense reports for this quarter is next Friday. Please make sure all receipts are attached and that each expense is categorized correctly. Reports submitted after the deadline will be processed in the following cycle. If you have any questions about what qualifies as a reimbursable expense, please refer to the updated policy document or reach out to the finance team directly."},
    {"category": "email", "text": "We are excited to announce the launch of our new customer portal. Starting next Monday, you will be able to manage your account, view invoices, track orders, and submit support requests all from one convenient dashboard. Your current login credentials will work with the new system. We've prepared a short tutorial video that walks you through the main features and I encourage you to watch it before your first login."},
    {"category": "email", "text": "I appreciate you taking the time to share your feedback on the new onboarding process. Your observations about the documentation gaps are spot on and we've already started working on updated guides that address the issues you raised. We take this kind of input seriously because it helps us improve the experience for everyone who joins the team. Please don't hesitate to share any additional thoughts as you continue to settle in."},
    {"category": "email", "text": "After careful consideration, the committee has decided to approve the funding request for the research initiative. The approved budget is slightly lower than the original request, but we believe it provides sufficient resources to achieve the primary objectives. A detailed budget breakdown will be sent separately. Please schedule a kickoff meeting with all principal investigators within the next two weeks to establish milestones and reporting requirements."},
    {"category": "email", "text": "I'm reaching out because I noticed that your subscription is set to expire at the end of this month. I wanted to make sure you're aware and to let you know about the renewal options available to you. If you renew before the expiration date, you can lock in the current rate for another year. Otherwise, the standard pricing will apply. I'd be happy to answer any questions or help you with the renewal process."},
])

# ── Category 10: Mixed / Conversational AI (10) ──
CORPUS.extend([
    {"category": "ai_conversation", "text": "That's a really interesting question. The short answer is that language models don't actually understand text the way humans do. They process patterns in data and generate responses based on statistical relationships between words and phrases. However, the practical effect can be remarkably similar to understanding, which is why the distinction matters so much for how we think about these systems and what we trust them to do."},
    {"category": "ai_conversation", "text": "I think there are a few things to consider here. First, the approach you're describing has been tried before and the results were mixed. The main challenge is that the computational cost scales quadratically with the input length, which makes it impractical for longer sequences. However, there have been some recent developments in approximate methods that might make it feasible. Would you like me to look into the specific techniques that have shown promise?"},
    {"category": "ai_conversation", "text": "You raise a valid point about the limitations of the current system. The problem isn't so much the algorithm itself but rather the data it's been trained on. If the training data contains biases, the model will inevitably reproduce those biases in its outputs. This is why it's so important to carefully curate training datasets and implement fairness constraints during the fine-tuning process. It's an area of active research and there's still a lot of work to be done."},
    {"category": "ai_conversation", "text": "Let me break this down into simpler terms. When you send a message, the model looks at all the words and their relationships to each other. It then generates a response one word at a time, choosing each word based on what came before it and what seems most likely to be helpful given the context. This process happens very quickly and the result is usually coherent, but it's fundamentally different from how a human would think about and compose a response."},
    {"category": "ai_conversation", "text": "I appreciate you sharing that with me. It sounds like you've been dealing with a lot of stress lately and I want you to know that it's completely normal to feel overwhelmed sometimes. There are a few strategies that might help you manage the workload better. Would you like me to suggest some time management techniques, or would it be more helpful to talk through how to prioritize the tasks you're facing right now?"},
    {"category": "ai_conversation", "text": "Based on what you've described, I think the issue is likely related to how the data is being serialized before it's sent to the API. The timestamps in your payload are formatted as strings but the endpoint expects Unix timestamps as integers. Try converting the datetime objects to epoch seconds before building the request body. That should resolve the validation error you're seeing. Let me know if you need help with the conversion code."},
    {"category": "ai_conversation", "text": "That's a great observation and it connects to something I've been thinking about as well. The trend toward smaller, more efficient models is driven by practical deployment constraints. Not everyone has access to massive compute infrastructure, and for many applications a smaller model that runs locally provides better latency, lower cost, and greater privacy than a larger model accessed through an API. The tradeoff is capability, but that gap is narrowing rapidly."},
    {"category": "ai_conversation", "text": "I want to make sure I'm giving you accurate information here, so let me clarify something. The approach you're asking about does work in theory, but there are important caveats that are often overlooked in practice. The results depend heavily on the quality of the input data and the specific configuration parameters used. I'd recommend starting with a small-scale test to validate the approach before committing to a full implementation."},
    {"category": "ai_conversation", "text": "Here's how I would approach this problem. Start by defining the success criteria clearly so you know what a good outcome looks like. Then break the project into the smallest possible independent tasks. Tackle the riskiest or most uncertain tasks first because those are the ones most likely to change your plan. Build in checkpoints where you evaluate progress and adjust direction if needed. The key is to maintain flexibility while keeping momentum."},
    {"category": "ai_conversation", "text": "I don't think there's a single right answer to this question. It really depends on your specific situation and priorities. If speed is the most important factor, then the first option is probably better. If long-term maintainability matters more, then the second approach has significant advantages even though it takes more time upfront. I can help you think through the tradeoffs in more detail if you'd like to share more about your constraints."},
])


def build_corpus():
    """Shuffle and split corpus into train (80) and holdout (20)."""
    # Verify we have 100 samples
    assert len(CORPUS) == 100, f"Expected 100 samples, got {len(CORPUS)}"

    # Stratified split: 8 from each category for train, 2 for holdout
    categories = {}
    for sample in CORPUS:
        cat = sample["category"]
        if cat not in categories:
            categories[cat] = []
        categories[cat].append(sample)

    train = []
    holdout = []

    for cat, samples in categories.items():
        random.shuffle(samples)
        train.extend(samples[:8])
        holdout.extend(samples[8:])

    random.shuffle(train)
    random.shuffle(holdout)

    assert len(train) == 80, f"Expected 80 train, got {len(train)}"
    assert len(holdout) == 20, f"Expected 20 holdout, got {len(holdout)}"

    # Stats
    print(f"Corpus: {len(CORPUS)} samples across {len(categories)} categories")
    print(f"Train:  {len(train)} samples")
    print(f"Holdout: {len(holdout)} samples")
    print(f"\nCategory distribution:")
    for cat in sorted(categories):
        t = sum(1 for s in train if s["category"] == cat)
        h = sum(1 for s in holdout if s["category"] == cat)
        print(f"  {cat:<20} train: {t}  holdout: {h}")

    # Character stats
    train_chars = sum(len(s["text"]) for s in train)
    holdout_chars = sum(len(s["text"]) for s in holdout)
    print(f"\nTotal characters: train={train_chars:,}  holdout={holdout_chars:,}")

    return train, holdout


def save_corpus():
    """Build and save corpus to JSON files."""
    corpus_dir = Path(__file__).parent / "corpus"
    corpus_dir.mkdir(exist_ok=True)

    train, holdout = build_corpus()

    with open(corpus_dir / "train.json", "w") as f:
        json.dump(train, f, indent=2)

    with open(corpus_dir / "holdout.json", "w") as f:
        json.dump(holdout, f, indent=2)

    print(f"\nSaved to {corpus_dir}/train.json and holdout.json")


if __name__ == "__main__":
    save_corpus()
