"""
HLC Autoresearch - Config
===========================
THIS IS THE FILE THE AGENT MODIFIES.

Every tunable parameter for the HLC compression system lives here.
The agent edits this file, runs evaluate.py, checks the score,
keeps improvements, discards regressions.

DO NOT put evaluation logic here. That stays in evaluate.py (read-only).
"""

# SYMBOL MAP - 900 entries

SYMBOL_MAP = {
    'about': '8',
    'access': 'ĳ',
    'accessible': 'Ȋ',
    'account': 'ļ',
    'accounts': 'å',
    'accuracy': 'ݻ',
    'achieve': 'č',
    'acquisition': 'ۈ',
    'across': 'U',
    'action': 'ş',
    'activate': 'ݽ',
    'activation': 'ѱ',
    'activities': '߀',
    'activity': 'ݾ',
    'actually': 'ˌ',
    'adding': 'ܡ',
    'additional': 'Ƨ',
    'address': 'ȭ',
    'adjust': 'ਫ',
    'adjusted': 'ʺ',
    'administered': 'ফ',
    'administration': 'ફ',
    'administrative': 'ښ',
    'advanced': 'ނ',
    'adverse': '٨',
    'affected': 'વ',
    'after': 'n',
    'against': 'ӓ',
    'aggregations': 'װ',
    'agreement': 'ہ',
    'all': '1',
    'allows': 'ʓ',
    'almost': 'ԃ',
    'already': 'Ɗ',
    'alternatives': 'ݝ',
    'always': 'ੴ',
    'amiodarone': 'ࡷ',
    'among': 'í',
    'an': 'H',
    'analysis': 'Ɲ',
    'analytics': '۴',
    'and': '+',
    'announced': 'ٹ',
    'annual': '୲',
    'answer': 'ʒ',
    'anxiety': 'Î',
    'any': '5',
    'anything': 'ޅ',
    'appears': 'ढ',
    'application': 'ƺ',
    'apply': 'ô',
    'approach': 'ƃ',
    'appropriate': '٧',
    'approval': 'ކ',
    'approved': 'އ',
    'approximately': 'א',
    'arbitration': '૧',
    'archaeological': 'ࡲ',
    'architecture': 'ƛ',
    'are': '<',
    'argument': 'ࢀ',
    'arising': 'Ԍ',
    'around': 'ʑ',
    'artificial': 'ג',
    'as': 'Q',
    'assessment': 'ɕ',
    'assistance': 'ૠ',
    'associated': 'ɔ',
    'assumption': 'ʧ',
    'at': 'c',
    'attached': 'ފ',
    'attorney': 'ӯ',
    'attribute': 'ۄ',
    'audit': 'ਛ',
    'authentication': 'Ɠ',
    'authorization': 'ܙ',
    'automated': 'ۅ',
    'automatic': 'ۆ',
    'automatically': 'ֈ',
    'available': 'ƞ',
    'average': 'ࠉ',
    'back': 'È',
    'based': 'Ǥ',
    'be': 'b',
    'because': 'l',
    'been': ']',
    'before': 'e',
    'behavior': 'ʷ',
    'behind': 'ʐ',
    'believe': 'Ǎ',
    'below': 'ࠊ',
    'better': 'ʏ',
    'between': 'N',
    'board': 'ઉ',
    'both': 'Ք',
    'boundaries': 'ב',
    'breach': 'ބ',
    'browser': 'Ȭ',
    'building': 'Փ',
    'business': 'ʶ',
    'but': '9',
    'by': 'L',
    'calendar': 'כ',
    'can': '|',
    'cancellation': 'ԛ',
    'capacity': 'ʵ',
    'cardiovascular': 'ࡺ',
    'categories': 'ڶ',
    'center': 'ř',
    'certificate': 'ė',
    'chain': 'ԭ',
    'change': 'ð',
    'changed': 'Ӎ',
    'changes': 'ǃ',
    'charging': 'ಀ',
    'class': 'ӏ',
    'clause': 'Ծ',
    'clean': 'ࢸ',
    'climate': 'Ƶ',
    'clinical': 'Ӈ',
    'code': 'Ֆ',
    'coffee': 'ǌ',
    'collaboration': 'Ϧ',
    'collection': 'ڵ',
    'combination': '٣',
    'commission': 'ơ',
    'commitment': 'Ԩ',
    'committee': 'ۏ',
    'common': '೧',
    'communication': 'Ӭ',
    'company': 'ē',
    "company's": 'छ',
    'compared': 'ޗ',
    'compatibility': 'ǵ',
    'compelling': 'ւ',
    'compensation': '੩',
    'competitive': 'ࠐ',
    'complete': 'ޘ',
    'completely': 'ƙ',
    'completing': 'ʇ',
    'complex': 'ʌ',
    'complexity': 'ڲ',
    'compliance': 'ଔ',
    'complimentary': 'ք',
    'component': 'ō',
    'compressions': 'ɸ',
    'computational': 'ƫ',
    'concentrations': 'ӳ',
    'conditions': 'Ƴ',
    'conference': 'શ',
    'configuration': 'Ƙ',
    'configure': 'ɰ',
    'configured': 'ڱ',
    'confirm': 'ӌ',
    'connection': 'ڰ',
    'connections': 'Ϫ',
    'consecutive': 'ڴ',
    'consider': 'ǖ',
    'consistent': 'گ',
    'consistently': 'צ',
    'construction': 'ɝ',
    'consumer': 'ݺ',
    'consumers': 'ٴ',
    'consumption': 'ಠ',
    'containing': 'Ӻ',
    'content': 'ĵ',
    'continuous': 'ژ',
    'contract': 'ޜ',
    'contractual': 'ಢ',
    'control': 'ą',
    'controlling': 'Ӑ',
    'conventional': 'ɿ',
    'conversation': 'פ',
    'cooperative': 'Ԗ',
    'correlation': 'Շ',
    'cost': 'ǽ',
    'costs': 'ə',
    'could': 'ǎ',
    'countries': 'ń',
    'create': 'ò',
    'created': 'թ',
    'creating': 'ޠ',
    'credentials': 'Ƹ',
    'critical': 'ɡ',
    'current': 'Ɖ',
    'currently': 'ǳ',
    'custom': 'ț',
    'customer': 'ǆ',
    'customers': 'ɲ',
    'daily': 'Ɇ',
    'data': 'F',
    'database': 'ޣ',
    'dataset': 'ø',
    'day': 'Ô',
    'days': 'Y',
    'debugging': 'ۯ',
    'decision': 'ʮ',
    'deduplication': 'ڌ',
    'default': 'ӈ',
    'degradation': 'Ԑ',
    'deletion': 'җ',
    'delivery': 'ޥ',
    'demonstrate': 'ي',
    'demonstrated': '३',
    'demonstrates': 'Ǐ',
    'department': 'ڪ',
    'dependencies': 'ȷ',
    'depending': '۲',
    'deployment': 'Ʀ',
    'design': 'ö',
    'details': 'ķ',
    'development': 'Ⱦ',
    'diagnosis': 'ی',
    'dietary': 'অ',
    'difference': 'ڨ',
    'different': 'Ɓ',
    'direction': 'ɯ',
    'directly': '߄',
    'disaster': 'ҟ',
    'disclaimer': 'ԝ',
    'disclosure': 'ʹ',
    'discovered': 'ࠨ',
    'discrepancy': 'ȍ',
    'discussed': 'ɮ',
    'discussion': 'ԣ',
    'discussions': 'Ƚ',
    'disproportionately': 'Ղ',
    'distinction': 'ײ',
    'distributed': 'ڹ',
    'distributes': 'ਊ',
    'district': 'ח',
    'document': 'ʭ',
    'documented': 'ୟ',
    'documents': '۷',
    "doesn't": 'ࡐ',
    'dollars': '੪',
    "don't": 'ǻ',
    'down': 'Ϲ',
    'downtown': 'ӎ',
    'duplicate': 'ň',
    'duration': '߉',
    'during': 'y',
    'each': 'w',
    'early': 'ĭ',
    'education': '۸',
    'effect': 'ܛ',
    'effective': 'ɭ',
    'effects': 'ݭ',
    'efficiency': 'ೲ',
    'efficient': '۹',
    'eight': 'જ',
    'eighteen': 'ߋ',
    'eighty': 'ॺ',
    'either': 'ॻ',
    'elasticity': 'ࡻ',
    'electrocardiogram': 'ɚ',
    'elevated': 'ન',
    'embeddings': 'ï',
    'emergency': 'ۻ',
    'emissions': 'ې',
    'employee': 'ઽ',
    'employees': 'Ϣ',
    'employment': 'Ǵ',
    'encryption': 'ڤ',
    'endpoint': 'ݟ',
    'endpoints': 'ڃ',
    'energy': 'ŝ',
    'enforcement': 'ر',
    'engineering': 'ق',
    'enough': 'ѻ',
    'enterprise': 'ܪ',
    'entire': 'ࣉ',
    'entirely': 'ן',
    'environment': 'Ơ',
    'error': 'Ȇ',
    'establish': 'ۼ',
    'estimated': 'ӡ',
    'evaluating': 'Ȍ',
    'even': 'ʃ',
    'evening': 'ŕ',
    'event': 'ԧ',
    'events': 'ӷ',
    'every': 'v',
    'everyone': 'Ș',
    "everyone's": 'ԯ',
    'everything': 'ɏ',
    'evidence': 'ߚ',
    'exceeded': 'ߛ',
    'exceeding': 'ۉ',
    'execution': 'ܐ',
    'existing': 'ߜ',
    'expansion': 'ܒ',
    'expected': 'ସ',
    'experience': 'ƥ',
    'experiencing': 'ˡ',
    'experiment': 'ü',
    'explicitly': 'ߟ',
    'exposure': 'ঢ়',
    'expressions': 'ࠎ',
    'extension': 'ٯ',
    'facilities': 'ݔ',
    'factors': 'ࡗ',
    'failure': 'ۊ',
    'failures': 'ߡ',
    'faster': '߇',
    'father': 'ঐ',
    'faucet': 'ȿ',
    'features': 'ȗ',
    'fifteen': 'ࡠ',
    'fifty': 'ઢ',
    'file': 'Ə',
    'filter': 'ঊ',
    'finally': 'Ȫ',
    'find': 'á',
    'findings': 'ʬ',
    'first': 'A',
    'five': 'p',
    'follow': 'é',
    'following': 'ɫ',
    'for': '@',
    'forty': 'Ԥ',
    'forward': 'ӆ',
    'foundation': 'ڡ',
    'four': 'E',
    'fourteen': 'ã',
    'framework': 'ƴ',
    'from': '%',
    'frustration': 'ת',
    'full': 'ϥ',
    'funding': 'ࡨ',
    'general': 'Ǝ',
    'generate': 'ę',
    'generation': 'ڠ',
    'gently': 'ক',
    'geographic': 'ɼ',
    'getting': 'ƶ',
    'gigabyte': 'Հ',
    'gigabytes': 'त',
    'good': 'Ͻ',
    'gradually': 'ǰ',
    'grandfather': 'ĉ',
    'group': 'Ú',
    'growth': 'š',
    'had': 'j',
    'handle': 'ÿ',
    'happened': '౹',
    'happening': 'ʉ',
    'harder': 'य़',
    'has': '_',
    'have': '[',
    'header': 'ɷ',
    'health': 'œ',
    'here': 'ˈ',
    'hierarchical': 'נ',
    'higher': 'ɧ',
    'highest': 'ବ',
    'his': 'ϫ',
    'historical': 'Ʃ',
    'history': 'ӂ',
    'home': 'Չ',
    'hour': 'प',
    'hours': 'o',
    'how': 'ǀ',
    'human': 'ଭ',
    'hundred': 'R',
    'hypertension': 'ॾ',
    'hypothesis': 'Ǉ',
    "i've": 'ʛ',
    'identified': 'ܧ',
    'identifier': 'ڝ',
    'identifies': 'Ն',
    'if': '6',
    'imaging': 'ʝ',
    'immediately': 'ؽ',
    'implement': 'ܞ',
    'implemented': 'ԍ',
    'implementing': 'ȶ',
    'improvement': 'Ɵ',
    'improvements': '٢',
    'improves': 'Ç',
    'improving': 'ܠ',
    'in': 'Z',
    'include': 'Ɩ',
    'included': 'Â',
    'includes': '౽',
    'including': 'ɪ',
    'inconsistent': 'Ԯ',
    'increase': 'ċ',
    'increased': 'Ӧ',
    'increasing': 'Ɍ',
    'incremental': 'ػ',
    'independently': 'ǲ',
    'indicates': 'ɩ',
    'individual': 'Ɋ',
    'individuals': 'ૐ',
    'industrial': 'എ',
    'industries': 'ދ',
    'industry': 'ݙ',
    'information': 'ƒ',
    'infrastructure': 'խ',
    'infringement': 'ɽ',
    'initialize': 'ഔ',
    'initiating': 'ڟ',
    'inspection': '૨',
    'instead': 'Ӏ',
    'institutional': 'ړ',
    'institutions': 'س',
    'instructions': 'ם',
    'instrument': 'ɐ',
    'insurance': 'ܥ',
    'integration': 'ظ',
    'intellectual': 'ડ',
    'interest': 'ಒ',
    'interesting': 'Ւ',
    'intermediate': 'ঈ',
    'intermittent': 'ɾ',
    'internal': 'æ',
    'international': '૪',
    'interval': 'ಌ',
    'interventions': 'ڋ',
    'into': 'В',
    'introducing': 'Ǫ',
    'introduction': 'ˣ',
    'investigation': 'ջ',
    'investment': 'ࡼ',
    'invitation': 'ղ',
    'is': '$',
    "isn't": 'ԟ',
    'issue': 'ĺ',
    'it': '7',
    "it's": 'А',
    'its': 'ӊ',
    'itself': 'ট',
    'jurisdiction': 'ଛ',
    'jurisdictions': 'ଊ',
    'just': 'S',
    'keep': 'ê',
    'kitchen': 'ࢄ',
    'know': 'Ȃ',
    'language': 'Ǔ',
    'languages': 'Ǚ',
    'largest': 'Ӣ',
    'last': 'Ǘ',
    'latency': 'ҥ',
    'leadership': 'ږ',
    'learning': 'ƿ',
    'least': 'ૡ',
    'less': 'ʽ',
    'let': 'ˎ',
    'level': 'ŷ',
    'levels': 'ӭ',
    'liability': 'ӗ',
    'library': 'Ï',
    'lifestyle': 'Ԃ',
    'light': 'ଞ',
    'like': 'Ձ',
    'limitation': 'ߑ',
    'limited': 'ݹ',
    'litigation': 'ચ',
    'located': 'ǅ',
    'looking': 'ȧ',
    'machine': 'ࢍ',
    'made': 'Մ',
    'magnitude': 'ɦ',
    'maintain': 'ĩ',
    'maintained': 'ռ',
    'maintenance': 'Խ',
    'make': 'ƕ',
    'making': 'ʎ',
    'management': 'ɉ',
    'manager': 'қ',
    'manufacturing': 'չ',
    'market': 'ǟ',
    'material': 'ݖ',
    'materials': 'ܬ',
    'may': 'ϱ',
    'measure': 'ʣ',
    'measurements': 'ԫ',
    'measuring': 'ࢨ',
    'mechanism': 'Ʋ',
    'mediation': 'ऴ',
    'meeting': 'Ƣ',
    'megabytes': 'ܭ',
    'memory': 'ভ',
    'message': 'ǂ',
    'migration': 'Պ',
    'milligrams': 'Ϸ',
    'millimeters': 'ಪ',
    'million': 'ϸ',
    'milliseconds': 'ద',
    'minimum': 'फ़',
    'minute': 'ʍ',
    'minutes': 'Ɣ',
    'model': 'ȁ',
    'moderate': 'ಇ',
    'modification': 'ݵ',
    'module': 'Ǟ',
    'monitoring': 'ڎ',
    'month': 'Þ',
    'monthly': 'ؾ',
    'months': 'Ӫ',
    'more': '`',
    'morning': 'ҙ',
    'most': 't',
    'must': 'ɒ',
    'need': 'Ց',
    'needs': 'ଉ',
    'negative': 'ಖ',
    'network': 'ľ',
    'never': 'ϗ',
    'new': '2',
    'next': 'B',
    'nine': 'ձ',
    'ninety': 'ϧ',
    'nobody': 'ک',
    'not': 's',
    'nothing': 'ɗ',
    'notice': 'ŏ',
    'notification': 'ט',
    'notifications': 'ո',
    'now': 'ʿ',
    'obligation': 'ތ',
    'obligations': '୮',
    'observation': 'ȼ',
    'observed': 'ಛ',
    'of': 'X',
    'office': 'ह',
    'officials': 'ࠃ',
    'on': 'V',
    'one': '}',
    'only': 'ʀ',
    'operations': 'Ö',
    'opportunities': 'շ',
    'or': '*',
    'order': 'ű',
    'organization': 'છ',
    'organizations': 'ڐ',
    'other': 'Ͼ',
    'otherwise': 'ݏ',
    'our': '\\',
    'out': '0',
    'outcomes': 'ర',
    'output': 'ʆ',
    'over': 'O',
    'overall': 'î',
    'override': 'ಏ',
    'parking': 'ॶ',
    'participants': 'ભ',
    'party': 'ࢳ',
    'password': 'ȑ',
    'passwords': 'ٮ',
    'patient': 'ࢯ',
    'patients': 'બ',
    'patterns': 'ƾ',
    'payment': 'Ҏ',
    'payments': 'Ԇ',
    'people': 'ݍ',
    'per': 'Ǡ',
    'percent': 'P',
    'percentage': 'ഗ',
    'performance': 'Ƒ',
    'period': 'ŋ',
    'permissions': 'ج',
    'persists': 'ש',
    'personal': 'ϛ',
    'phase': 'ԕ',
    'physical': 'ɍ',
    'place': 'Ë',
    'plan': 'ϡ',
    'planning': 'ತ',
    'platform': 'ʂ',
    'please': 'ƅ',
    'point': '#',
    'polarization': 'Ԝ',
    'policy': 'ŗ',
    'portfolio': 'ࢾ',
    'position': 'ě',
    'positioning': 'Ӆ',
    'positions': 'ݒ',
    'positive': 'ʦ',
    'potential': 'ǯ',
    'practical': 'ݓ',
    'practices': 'ल',
    'preferences': 'ڷ',
    'premium': 'ҍ',
    'prescribed': 'व',
    'present': 'ǧ',
    'presentation': 'Ƿ',
    'presenting': 'ࡥ',
    'pressed': 'Ҍ',
    'pressure': 'ݰ',
    'prevent': 'ɜ',
    'previous': 'Ռ',
    'pricing': 'ҋ',
    'primary': 'Ȥ',
    'prioritize': 'ڄ',
    'problem': 'Ʒ',
    'process': 'ď',
    'processed': 'ɤ',
    'processing': 'Ƥ',
    'produce': 'ࢷ',
    'product': 'ҁ',
    'production': 'Ǜ',
    'professional': 'Ԟ',
    'program': '२',
    'project': 'ĕ',
    'projects': 'ಫ',
    'proper': 'ޖ',
    'properly': 'Ǒ',
    'property': 'ä',
    'propose': 'ȣ',
    'protection': 'ఢ',
    'provided': 'Ӳ',
    'public': 'ֆ',
    'purchase': 'ׯ',
    'purpose': 'ĝ',
    'quality': 'Ȣ',
    'quarter': 'Ҁ',
    'quarterly': 'ɢ',
    'queries': 'ࢺ',
    'question': 'ʤ',
    'quiet': 'च',
    'rate': 'ǡ',
    'rates': 'ǚ',
    'rather': 'ǝ',
    'reaching': 'ವ',
    'readable': 'ϯ',
    'reading': 'গ',
    'real': 'ϟ',
    'reasonable': 'ڗ',
    'receive': 'ॱ',
    'receiving': '੬',
    'recommend': 'Ǯ',
    'recommended': 'ȸ',
    'record': 'ũ',
    'recovery': 'ˁ',
    'reduced': 'ࢿ',
    'reducing': '৶',
    'reduction': 'ǭ',
    'reductions': 'ࡪ',
    'reference': 'ɠ',
    'regardless': 'ܨ',
    'region': 'ࡱ',
    'regional': 'ఌ',
    'regular': 'Ǌ',
    'regulation': 'ʰ',
    'regulations': 'Ͽ',
    'regulatory': 'Ʌ',
    'related': 'ࣃ',
    'relationship': 'ה',
    'release': 'Ѿ',
    'reliability': 'Ÿ',
    'remaining': '۰',
    'remains': 'ѽ',
    'remediation': 'ದ',
    'remembered': 'ࠄ',
    'remove': 'ó',
    'removeeventlistener': 'ಭ',
    'renewal': 'ȡ',
    'replacement': 'ا',
    'report': 'ʋ',
    'reported': 'ɛ',
    'reporting': 'ɟ',
    'request': 'ŀ',
    'requested': 'ݠ',
    'requests': 'ʗ',
    'require': 'û',
    'required': 'ೞ',
    'requirements': 'ư',
    'requires': '੮',
    'requiring': 'ݡ',
    'research': 'ƽ',
    'residential': 'Ը',
    'resolution': 'Ʉ',
    'resolved': 'ڙ',
    'resource': 'ȏ',
    'resources': 'ɞ',
    'respiratory': 'ಈ',
    'response': 'į',
    'restrictions': 'ف',
    'results': 'ǁ',
    'retaliation': 'ǩ',
    'retention': 'ݢ',
    'returns': 'Ԭ',
    'revealed': 'ע',
    'reveals': 'Ŷ',
    'revenue': 'ࣈ',
    'reverse': 'ஓ',
    'review': 'ő',
    'reviews': 'ʔ',
    'right': 'Ø',
    'risk': 'Ϟ',
    'running': 'ȟ',
    'same': 'Լ',
    'satisfaction': 'غ',
    'saturday': 'ȹ',
    'scheduled': 'Ǭ',
    'scheduling': 'Ϩ',
    'schema': 'ৼ',
    'scoring': 'ɶ',
    'screening': '୦',
    'screw': 'ԙ',
    'search': 'ਕ',
    'season': 'ƚ',
    'second': 'Ȉ',
    'seconds': 'उ',
    'section': 'ˆ',
    'securities': 'ñ',
    'security': 'ʖ',
    'segment': 'Ӛ',
    'sending': 'ۀ',
    'separate': '೬',
    'server': 'ӣ',
    'service': 'đ',
    'services': 'ǐ',
    'session': 'ऌ',
    'settings': 'Ʈ',
    'seven': 'ϖ',
    'seventy': 'ଣ',
    'several': 'Ѽ',
    'severe': 'খ',
    'shared': 'ষ',
    'she': 'ʄ',
    'should': 'z',
    "shouldn't": 'ࢵ',
    'show': 'ç',
    'shows': '୬',
    'side': 'Å',
    'significant': 'Ɛ',
    'significantly': 'մ',
    'since': 'ध',
    'single': 'Ӡ',
    'six': 'Ü',
    'sixteen': 'ȉ',
    'sixty': 'ମ',
    'size': 'Ի',
    'small': 'Ԏ',
    'so': 'ǋ',
    'social': 'Ȁ',
    'software': 'ೱ',
    'some': 'Ժ',
    'something': 'Ƭ',
    'sometimes': 'ݬ',
    'specific': 'Ɯ',
    'specification': 'ڍ',
    'specified': 'ஏ',
    'standard': 'ഇ',
    'start': 'ë',
    'started': 'Ȟ',
    'starting': 'ʜ',
    'state': 'ϔ',
    'statistics': 'ޚ',
    'status': 'ņ',
    'still': 'ƍ',
    'stone': 'ӝ',
    'storage': 'ѹ',
    'stories': 'ۑ',
    'straightforward': 'դ',
    'strategy': 'Ƽ',
    'strongest': 'ݲ',
    'structural': 'ಷ',
    'structure': 'ڻ',
    'structured': 'Ѹ',
    'structures': 'ܫ',
    'studies': 'ۮ',
    'subject': 'ݕ',
    'subscription': 'Ƕ',
    'suggest': 'ȝ',
    'suggesting': 'Ж',
    'suggests': 'ì',
    'supervised': 'վ',
    'support': 'þ',
    'supports': 'Ȏ',
    'surface': 'ѷ',
    'switching': 'Í',
    'symptoms': 'ݛ',
    'system': 'ʈ',
    'systems': 'Ȝ',
    'talking': 'ˍ',
    'target': 'ڽ',
    'team': 'ɻ',
    'technologies': 'ع',
    'technology': 'ٸ',
    'temperature': 'ϰ',
    'temperatures': 'Ǩ',
    'ten': '4',
    'termination': 'Ϯ',
    'terms': 'Ԋ',
    'tested': 'ਬ',
    'testing': 'ɳ',
    'tests': 'ॽ',
    'than': 'g',
    'that': '~',
    "that's": 'ਭ',
    'the': '^',
    'their': 'D',
    'them': 'ȇ',
    'then': 'Ǽ',
    'therapeutic': 'Ȼ',
    'therapy': 'स',
    'there': 'ˉ',
    "there's": 'Ѷ',
    'these': 'ˠ',
    'they': 'ǥ',
    "they're": 'झ',
    'thing': 'Ý',
    'think': 'ƌ',
    'thinking': 'ƻ',
    'third': 'ୡ',
    'thirty': 'M',
    'this': '!',
    'those': 'ɵ',
    'though': 'ӛ',
    'thought': 'à',
    'thousand': 'q',
    'three': 'm',
    'through': 'f',
    'time': '3',
    'timeline': 'ǿ',
    'times': 'ˑ',
    'to': 'W',
    'total': 'Ź',
    'totaling': 'ԅ',
    'traffic': 'Ѵ',
    'training': 'ƭ',
    'transaction': 'ɖ',
    'transition': 'ٵ',
    'transitioning': 'ȃ',
    'treatment': 'É',
    'trial': 'ק',
    'trust': 'ਓ',
    'trying': 'ۃ',
    'tuesday': 'ष',
    'twelve': 'Ӗ',
    'twenty': 'k',
    'two': 'x',
    'typically': 'ݸ',
    'under': 'J',
    'understand': 'Ɂ',
    'unsupervised': 'ŵ',
    'until': 'ɴ',
    'up': 'G',
    'upcoming': 'Ǿ',
    'update': 'ʅ',
    'updated': 'Ǧ',
    'updates': 'ĸ',
    'use': 'Ϻ',
    'used': 'ˀ',
    'users': 'ˏ',
    'using': 'Ǆ',
    'vaccination': 'ɓ',
    'vaccine': 'ϻ',
    'variables': 'ϳ',
    'vegetables': 'ರ',
    'vehicle': 'ಮ',
    'verified': 'ʙ',
    'version': 'Ѱ',
    'walking': 'ઓ',
    'warfarin': 'Ջ',
    'warranties': 'Ϥ',
    'was': '>',
    'watched': 'Ѯ',
    'water': 'அ',
    'way': 'Ȩ',
    'we': 'T',
    "we're": 'ԇ',
    'week': 'ß',
    'weekend': 'य',
    'weekly': 'ل',
    'weeks': 'ȯ',
    'weight': 'ਫ਼',
    'well': 'ϼ',
    'were': 'ȴ',
    'what': 'Ù',
    'when': 'r',
    'where': 'Ȯ',
    'whether': 'ѭ',
    'which': 'h',
    'while': 'Ƌ',
    'whistleblower': 'ࢢ',
    'who': 'Û',
    'will': 'd',
    'window': 'ǜ',
    'with': '&',
    'within': 'K',
    'without': 'Ɨ',
    'work': 'Ӝ',
    'workflows': 'எ',
    'working': 'Ț',
    'would': '{',
    'wrong': 'ഐ',
    'year': 'Ѝ',
    'years': 'u',
    'yesterday': 'ɘ',
    'you': ';',
    "you'll": '੨',
    "you're": 'ǹ',
    'your': 'C',
    'yourself': 'ત',
    'zero': 'ˢ',
}

# PHRASE CODEBOOK - 600 entries

PHRASE_CODEBOOK = {
    'thank you': 'β',
    'let me know': 'ι',
    'due to': 'υ',
    'at least': 'Β',
    'up to': 'Ι',
    'based on': 'Π',
    'according to': 'Σ',
    'should be': 'Е',
    'has been': 'ҿ',
    'have been': 'З',
    'will be': 'И',
    'need to': 'ѓ',
    'want to': 'М',
    'have to': 'Н',
    'used to': 'О',
    'make sure': 'Ҝ',
    'we should also': 'Њ',
    'think about': 'Ң',
    'and the': 'Ҧ',
    'to the': 'ҧ',
    'in the': 'Ҩ',
    'of the': 'ҩ',
    'with the': 'Ҫ',
    'that the': 'ҫ',
    'for the': 'Ҭ',
    'on the': 'ҭ',
    'through the': 'Ү',
    'by the': 'Ұ',
    'the new': 'ұ',
    'from the': 'Ҳ',
    'about the': 'ҳ',
    'the current': 'ҵ',
    'for your': 'Ҷ',
    'on your': 'ҷ',
    'the next': 'Ҿ',
    'thank you for': 'Ā',
    'the first': 'Ă',
    'let me': 'Ć',
    'within the next two weeks': 'Ĉ',
    'at the': 'ј',
    'with a': 'љ',
    'all the': 'Č',
    'the system': 'Ď',
    'we need': 'Đ',
    'in the next': 'ғ',
    'within the next': 'ˮ',
    'by the end of this week': 'ʹ',
    'thinking about': 'Ĝ',
    "i've been": 'Ġ',
    'the problem': 'Ĥ',
    'your account': 'Ħ',
    'i can': 'Ķ',
    'and i': 'Ĺ',
    'is that': 'Ł',
    'within the': 'Ń',
    'the upcoming': 'Ŋ',
    'we should': 'Œ',
    'i have': 'Ŕ',
    'we need to': 'Ř',
    'if you': 'À',
    'you have': 'Á',
    'the most': 'Ò',
    'rather than': 'ż',
    'one hundred': 'Ž',
    'the second': 'Ƃ',
    'during the': 'Ƈ',
    'before the': 'ƈ',
    'using the': 'Ǹ',
    'two weeks': 'Ǻ',
    'real time': 'ɹ',
    "i've been thinking about": 'Ή',
    'one hundred and': 'ή',
    'within the next two': 'ς',
    'the next two weeks': 'ϊ',
    'the problem is': 'ϑ',
    'next two weeks': 'ϓ',
    'associated with': 'й',
    'twelve percent': 'л',
    'implementing a': 'с',
    'browser cache': 'ъ',
    'available for': 'ы',
    'can be': 'я',
    'you for': 'ё',
    'to make': 'ђ',
    'two thousand': 'і',
    'the end of': 'ѡ',
    'the next two': 'ѩ',
    'the same': '¡',
    'because the': '¢',
    'when the': '£',
    'you can': '¤',
    'is the': '¥',
    'under the': '¦',
    'more than': '§',
    'than the': '¨',
    'i think': '©',
    'across the': 'ª',
    'to your': '«',
    'but the': '¬',
    'the right': '®',
    'trying to': '¯',
    'over the': '°',
    'and a': '±',
    'in a': '²',
    'if the': '³',
    'to a': '´',
    'was a': 'µ',
    'of our': '¶',
    'it was': '·',
    'from a': '¸',
    'for a': '¹',
    'the cost': 'º',
    'we have': '»',
    'do not': '¼',
    'a single': '½',
    'does not': '¾',
    'to be': '¿',
    'of a': 'Ã',
    'the best': 'Ä',
    'the end': 'Æ',
    'as a': 'Ê',
    'which is': 'Ð',
    'that you': 'Ñ',
    'into the': 'Õ',
    'after the': '×',
    'between the': 'â',
    'since the': 'è',
    'not a': 'õ',
    'i recommend': '÷',
    'the entire': 'ù',
    'that our': 'ú',
    'to our': 'ý',
    'of this': 'ā',
    'needs to': 'ă',
    'the old': 'ć',
    'so you': 'Ē',
    'thousand dollars': 'Ė',
    'intellectual property': 'Ę',
    'percent increase in': 'Ě',
    'percent of': 'Ğ',
    'hundred and': 'ğ',
    'percent increase': 'ġ',
    'three hundred': 'ģ',
    'million dollars': 'ĥ',
    'analysis of': 'ħ',
    'totaling approximately': 'Ī',
    'five hundred': 'ī',
    'rather than trying to': 'Ĭ',
    'hundred thousand': 'Į',
    'the primary': 'ı',
    'we need to implement': 'Ĳ',
    'personal information': 'Ľ',
    'increase in': 'Ŀ',
    'including but not limited to': 'ł',
    'in the first place.': 'Ň',
    'negative zero point': 'ŉ',
    'two to three': 'Ō',
    'exceeding one million rows': 'Ŏ',
    'within the next two weeks.': 'Ő',
    'two to three weeks': 'Ŗ',
    'the enterprise': 'Ś',
    'requests per minute with a': 'ś',
    'rather than trying': 'Ŝ',
    'including but not limited': 'Ş',
    'need to implement': 'Š',
    'two hundred': 'Ţ',
    'three weeks': 'ţ',
    'the cost of': 'Ť',
    'hundred thousand dollars': 'ť',
    'regardless of': 'ŧ',
    'requests per minute with': 'ū',
    'material adverse change': 'Ŭ',
    'the first place.': 'ŭ',
    'the distinction between': 'ů',
    'for at least four hours': 'Ű',
    'per minute with a burst': 'Ų',
    'a combination of': 'ų',
    'at the cost of slightly': 'Ŵ',
    'one point': 'Ż',
    'approximately one point': 'ž',
    'officials attribute the': 'ſ',
    'three hundred thousand': 'Ƅ',
    'in the first': 'Ɔ',
    'the difference between': 'ƣ',
    'two to three weeks and': 'ƨ',
    'requests per': 'ƪ',
    'one hundred and twenty': 'Ư',
    'to access your account': 'Ʊ',
    'around the': 'ƹ',
    'will include': 'ǈ',
    'about what': 'ǒ',
    'should begin': 'ǔ',
    'patients should': 'Ǖ',
    'the engineering': 'ǘ',
    'two hundred and': 'Ǣ',
    'pressure on the': 'ǣ',
    'fifteen minutes': 'ǫ',
    'scheduled maintenance': 'Ǳ',
    'exceeding one million': 'Ȅ',
    'after controlling for': 'ȅ',
    'thousand requests per': 'ȋ',
    'environment variables': 'Ȑ',
    'compared to': 'Ȓ',
    'have to think about.': 'ȓ',
    'would eliminate this': 'Ȕ',
    'indicates that': 'ȕ',
    'during peak': 'Ȗ',
    'i think the': 'ș',
    'frustration with the': 'Ƞ',
    'let me know if': 'ȥ',
    'to three': 'Ȧ',
    'to three weeks': 'ȩ',
    'the default': 'ȫ',
    'the most significant': 'Ȳ',
    'twenty percent': 'ȳ',
    'hundred requests per': 'ȵ',
    'is recommended': 'Ⱥ',
    'combination of': 'ɀ',
    'point three': 'ɂ',
    'approximately ninety': 'Ƀ',
    'should include': 'ɇ',
    'at the cost of': 'Ɉ',
    'the cost of slightly': 'ɋ',
    'than trying to': 'Ɏ',
    'thirty percent': 'ɑ',
    'will include a': 'ɣ',
    'against the': 'ɥ',
    'in this jurisdiction': 'ɨ',
    'through a': 'ɬ',
    'until the': 'ɱ',
    'include a': 'ɺ',
    'where the': 'ʁ',
    'the third': 'ʊ',
    'distinction between': 'ʕ',
    'starting conditions': 'ʘ',
    "you're experiencing": 'ʚ',
    'at least four hours': 'ʞ',
    'approximately eight': 'ʟ',
    'the next two weeks.': 'ʠ',
    'one hundred percent': 'ʡ',
    'requests per minute': 'ʢ',
    'minute with a burst': 'ʥ',
    'thousand dollars in': 'ʨ',
    'in the jurisdiction': 'ʩ',
    'access your account': 'ʪ',
    'regular expressions': 'ʫ',
    'assistance has been': 'ʯ',
    'the introduction of': 'ʱ',
    'through the lens of': 'ʲ',
    'binding arbitration': 'ʳ',
    'argument about what': 'ʴ',
    'within ninety days.': 'ʸ',
    'officials attribute': 'ʻ',
    'the assumption that': 'ʼ',
    'twenty years.': 'ʾ',
    'for the first': '˂',
    'the remaining': '˃',
    'a combination': '˄',
    'negative zero': '˅',
    'the scheduled': 'ˇ',
    'that actually': 'ˊ',
    'four thousand': 'ˋ',
    'minutes a day': 'ː',
    'the migration': '˒',
    'following the': '˓',
    'attribute the': '˔',
    'patients should be': '˕',
    'indicates that the': '˖',
    "the question isn't": '˗',
    'dollars in': '˘',
    'million dollars in': '˙',
    'related to': '˚',
    'difference between': '˛',
    'within twenty-four': '˜',
    'to three weeks and': '˝',
    'to prevent': '˞',
    'subject to': '˟',
    'but not limited to': '˥',
    'zero point': '˦',
    'hundred and twenty': '˧',
    'in the chain would': '˨',
    'his father': '˩',
    'ninety-one percent': '˪',
    'project management': '˫',
    'in plain language,': 'ˬ',
    'structures. in the': '˭',
    'verified emissions': '˯',
    'if you think about': '˰',
    'the center of the': '˱',
    'across three': '˲',
    'during peak hours': '˳',
    'the question': '˴',
    'first place.': '˵',
    'treating everyone': '˶',
    'one thousand': '˷',
    'i understand': '˸',
    'to implement': '˹',
    'the standard': '˺',
    'for at least four': '˻',
    'after controlling': '˼',
    'hundred and fifty': '˽',
    'depending on': '˾',
    'switching to': '˿',
    'should receive an': '̀',
    'thousand requests': '́',
    'per minute with a': '̂',
    'the software': '̃',
    'arising from': '̄',
    'including but not': '̅',
    'the regional': '̆',
    'you need': '̇',
    'up to two percent': '̈',
    'percent. the': '̉',
    'engineering team.': '̊',
    'strategy for': '̋',
    'tests run against': '̌',
    'forty-eight hours': '̍',
    'the most commonly': '̎',
    'the contract': '̏',
    'the previous': '̐',
    'network with': '̑',
    'fifteen to twenty': '̒',
    'this jurisdiction': '̓',
    'thousand dollars.': '̔',
    'and recovery': '̕',
    'social media': '̖',
    'is available': '̗',
    'before initiating': '̘',
    'approximately one': '̙',
    'requests per hour': '̚',
    'hundred megabytes': '̛',
    'physical activity': '̜',
    'for international': '̝',
    'causes the other.': '̞',
    'we need to switch': '̟',
    'the screw': '̠',
    'material adverse': '̡',
    'milligrams daily': '̢',
    'think the': '̣',
    'frustration with': '̤',
    'one million rows': '̥',
    'least four hours': '̦',
    'by approximately': '̧',
    'employees should': '̨',
    'data from': '̩',
    'permissions from': '̪',
    'most significant': '̫',
    'hundred requests': '̬',
    'business days. i': '̭',
    'alleges that the': '̮',
    'in twenty years.': '̯',
    'the total': '̰',
    'with four': '̱',
    'full-text search': '̲',
    'zero point three': '̳',
    'should include a': '̴',
    'cost of slightly': '̵',
    'the jurisdiction': '̶',
    'your integration': '̷',
    'the event': '̸',
    'the board': '̹',
    'has been updated': '̺',
    'eighteen percent': '̻',
    'engineering team': '̼',
    'in the meantime,': '̽',
    'and will include': '̾',
    'to invite you to': '̿',
    'upcoming product': '̀',
    'the introduction': '́',
    'through the lens': '͂',
    'instructions for': '̓',
    'fourteen percent': '̈́',
    'depending on the': 'ͅ',
    'changed the': '͆',
    'about three': '͇',
    'is expected': '͈',
    'a different': '͉',
    'ten minutes': '͊',
    'is the most': '͋',
    'recovery of': '͌',
    'period with': '͍',
    'at the cost': '͎',
    'pressure on': '͏',
    'six months.': '͐',
    'than trying': '͑',
    'the process': '͒',
    'expected to': '͓',
    'compared to the': '͔',
    'in the morning.': '͕',
    'to think about.': '͖',
    'would eliminate': '͗',
    'eighteen months': '͘',
    'analysis of the': '͙',
    'fifteen percent': '͚',
    'aligns with the': '͛',
    'higher than the': '͜',
    'the distinction': '͝',
    "doesn't produce": '͞',
    'of one thousand': '͟',
    'three levels of': '͠',
    "you're making a": '͡',
    'controlling for': '͢',
    'our analysis of': 'ͣ',
    'next two weeks.': 'ͤ',
    'presenting with': 'ͥ',
    'hundred percent': 'ͦ',
    'related to your': 'ͧ',
    'three weeks and': 'ͨ',
    'percent against': 'ͩ',
    'tier allows one': 'ͪ',
    'per minute with': 'ͫ',
    'to your account': 'ͬ',
    'under the terms': 'ͭ',
    'but not limited': 'ͮ',
    'data protection': 'ͯ',
    'the chain would': 'ͱ',
    'will be used to': 'Ͳ',
    'his grandfather': '͵',
    'at three in the': 'ͻ',
    'the permissions': 'ͽ',
    'thirty thousand': ';',
    'the majority of': 'Ϳ',
    'thirty seconds.': '΄',
    'thousand years.': '΅',
    'has resulted in': '·',
    'the certificate': 'Έ',
    'of intellectual': 'Ί',
    'starting in the': 'Ό',
    'plain language,': 'Ύ',
    'seventy percent': 'Α',
    'and recovery of': 'Γ',
    'the final three': 'Ε',
    'introduction of': 'Η',
    'you think about': 'Θ',
    'i have attached': 'Λ',
    'administered in': 'Μ',
    'presentation at': 'Ν',
    'the arbitration': 'Ξ',
    'assumption that': 'Ο',
    'cost of': 'Ρ',
    'adverse change': 'Τ',
    'the target': 'Υ',
    'two to': 'Φ',
    'eliminate this': 'Ϋ',
    'proposals from': 'ά',
    'to produce': 'έ',
    'increasing the': 'ΰ',
    "question isn't": 'α',
    'as the primary': 'γ',
    'instead of': 'δ',
    'back and forth': 'ε',
    'the memory': 'ζ',
    'with a maximum': 'η',
    'in under': 'θ',
    'across all': 'κ',
    'start by': 'λ',
    'four hours': 'μ',
    'your first': 'ν',
    'two weeks.': 'ξ',
    'appears to': 'ο',
    'to one hundred': 'π',
    'me know if': 'φ',
    'the difference': 'ψ',
    'a fourteen-day': 'ω',
    'everything she': 'ϋ',
    'should receive': 'ύ',
    'receive an': 'Ϗ',
    'three thousand': 'ϐ',
    'thousand years': 'ϒ',
    'using an': 'ϕ',
    'business days.': 'Ϙ',
    'clinical trial': 'ϙ',
    'with something': 'Ϛ',
    'not limited to': 'Ϝ',
    "and it's": 'ϝ',
    'like a': 'Ϡ',
    'the configured': 'ϣ',
    'eighty percent': 'ϩ',
    'mobile app': 'Ϭ',
    'the conference': 'ϭ',
    'has been moved': 'ϲ',
    'to two percent': 'ϴ',
    'to access your': 'ϵ',
    'leads to': '϶',
    'materials like': 'Ѐ',
    'are subject to': 'Ё',
    'injection site': 'Ђ',
    'thousand teams': 'Ѓ',
    'over three': 'Є',
    'improvement in': 'Ѕ',
    'to establish a': 'І',
    "you'll need to": 'Ї',
    'the leadership': 'Ј',
    'so you can': 'Љ',
    'structures. in': 'Ћ',
    'percent of the': 'Ќ',
    'a separate': 'Ў',
    'completing the': 'Џ',
    'every five': 'Б',
    'the source': 'Й',
    'thought it was': 'Л',
    'which override': 'С',
    'assistance has': 'Т',
    'the header': 'Ф',
    'you care about': 'Ц',
    'twenty minutes': 'Ч',
    'argument about': 'Ш',
    'to engage with': 'Щ',
    'the historical': 'Ъ',
    'a complete': 'Ы',
    'false positive': 'Ь',
    'one point four': 'Э',
    'is expected to': 'Я',
    'fifty thousand': 'б',
    'the assumption': 'в',
    'need to switch': 'г',
    'the center of': 'д',
    'center of the': 'е',
    'and patience.': 'ж',
    'everything is': 'з',
    'please submit': 'и',
    'have to think': 'к',
    "because we're": 'м',
    'requests per minute with a burst': 'П',
    'justifies the': 'Ҥ',
    'three percent': 'Р',
    'sixty percent': 'Ũ',
    'exceeding one': 'Δ',
    "you're making": 'ѐ',
    'at least four': 'Ҵ',
    'in real time.': 'ǉ',
    'appears to be': 'ȱ',
    'learning, you': 'Ͷ',
    'the first two': 'ѧ',
    "the company's": 'Ҟ',
    'the course of': 'Ļ',
    'or related to': 'Ņ',
    'minute with a': 'ƀ',
    'side effects.': 'Ψ',
    'risk factors.': 'ү',
    'including but': 'Ó',
    'the resulting': 'ΐ',
    'elasticity of': 'Ϊ',
    'assessment of': 'Ω',
    "isn't whether": 'К',
    'the requested': 'ѕ',
    'most commonly': 'Ċ',
    'everything on': 'Ĕ',
    'three million': 'Ĵ',
    'your existing': 'Ů',
    'force majeure': 'ѝ',
    'talking about': 'Ѫ',
    'one point two': 'ѫ',
    'access to the': 'Χ',
    'revealed that': 'ҽ',
    'answer from a': 'Һ',
    'with the most': 'х',
    'the weight of': 'ш',
    'you mentioned': 'ь',
    'the meantime,': 'Ѥ',
    'to invite you': 'χ',
    'invite you to': 'Κ',
    'by end of day': 'Г',
    'have attached': 'Д',
    'all employees': 'њ',
    'seven hundred': 'У',
    'within ninety': 'Ū',
    'the strongest': 'р',
    'a remediation': 'т',
    'warranties of': 'Ҹ',
    'to remove': 'ў',
    'use a': 'Ͱ',
    'you could': 'Ĩ',
    'to twenty': 'ί',
    'weeks and': 'ρ',
    'adapts to': 'Х',
    'the state': 'Ą',
    'year. the': 'Ŧ',
    'the terms': 'Ȱ',
    'up to two': 'ͷ',
    'the final': 'ͺ',
    'less than': 'ͼ',
    'audit and': 'Ώ',
    'access to': 'ώ',
    "there's a": 'τ',
    'minutes a': 'Ζ',
    'two point': 'ћ',
    'point two': 'ό',
    'the error': 'Қ',
    'through your': 'ї',
    'to six': 'ˤ',
    'the morning.': 'ͳ',
    'think about.': 'İ',
    'because they': 'Ю',
    'outcomes. it': 'а',
    'the evidence': 'Ì',
    'for our': 'Ά',
    'of one': 'σ',
    'the response': 'Ģ',
    'million rows': 'ź',
}

# VOWEL STRIPPING PARAMETERS
MIN_VOWEL_STRIP_LENGTH = 4

VOWEL_STRIP_EXCEPTIONS = {
    'area', 'audio', 'base', 'case', 'code', 'data',
    'false', 'file', 'idea', 'image', 'meta', 'mode',
    'node', 'none', 'note', 'null', 'queue', 'quote',
    'radio', 'rate', 'ratio', 'role', 'rule', 'state',
    'table', 'true', 'type', 'value', 'video',
}

PROTECTED_SHORTHAND = {
    'admin', 'afk', 'api', 'app', 'asap', 'auth', 'brb', 'btw',
    'css', 'db', 'dev', 'diy', 'doc', 'docs', 'eta', 'faq',
    'fomo', 'ftw', 'fyi', 'gg', 'gtg', 'html', 'idk', 'imho',
    'imo', 'info', 'irl', 'jk', 'js', 'lmk', 'lol', 'msg',
    'np', 'nvm', 'omg', 'omw', 'pic', 'pls', 'rofl', 'rsvp',
    'smh', 'sql', 'tbh', 'thx', 'tldr', 'tmi', 'ttyl', 'ty',
    'ui', 'url', 'ux', 'wip', 'wtf', 'yolo',
}

MORPHOLOGICAL_PATTERNS = [
    (r'^(.+?)tion$', 'tn'),
    (r'^(.+?)sion$', 'sn'),
    (r'^(.+?)ment$', 'mt'),
    (r'^(.+?)ness$', 'ns'),
    (r'^(.+?)able$', 'bl'),
    (r'^(.+?)ible$', 'bl'),
    (r'^(.+?)ity$', 'ty'),
    (r'^(.+?)ous$', 'us'),
    (r'^(.+?)ful$', 'fl'),
    (r'^(.+?)less$', 'ls'),
    (r'^(.+?)ling$', 'lng'),
    (r'^(.+?)ting$', 'tng'),
    (r'^(.+?)ning$', 'nng'),
    (r'^(.+?)ring$', 'rng'),
    (r'^(.+?)sing$', 'sng'),
    (r'^(.+?)ing$', 'ng'),
    (r'^(.+?)ily$', 'ly'),
    (r'^(.+?)ally$', 'ly'),
    (r'^(.+?)ly$', 'ly'),
    (r'^(.+?)ed$', 'd'),
    (r'^(.+?)er$', 'r'),
    (r'^(.+?)est$', 'st'),
    (r'^(.+?)es$', 's'),
    (r'^(.+?)s$', 's'),
]

MIN_BASE_LENGTH = 3
