"""
HLC Autoresearch - Config
===========================
THIS IS THE FILE THE AGENT MODIFIES.

Every tunable parameter for the HLC compression system lives here.
The agent edits this file, runs evaluate.py, checks the score,
keeps improvements, discards regressions.

DO NOT put evaluation logic here. That stays in evaluate.py (read-only).
"""

# SYMBOL MAP - 900 entries, optimized by corpus frequency x byte savings

SYMBOL_MAP = {
    'about': '8',
    'absolutely': 'ࡗ',
    'access': 'ĳ',
    'accessible': 'Ȋ',
    'account': 'ļ',
    'accounts': 'å',
    'accuracy': 'ݻ',
    'achieve': 'č',
    'acquisition': 'ۈ',
    'across': 'ǋ',
    'action': 'ş',
    'activate': 'ݽ',
    'activation': 'ѱ',
    'activities': '߀',
    'activity': 'ݾ',
    'actually': 'ˌ',
    'adding': 'ܡ',
    'additional': 'Ƨ',
    'address': 'ȭ',
    'adjusted': 'ʺ',
    'administered': 'ফ',
    'administration': 'ફ',
    'administrative': 'ښ',
    'advanced': 'ނ',
    'adverse': '٨',
    'affected': 'વ',
    'after': 'ǥ',
    'against': 'ӓ',
    'aggregations': 'װ',
    'agreement': 'ہ',
    'all': '1',
    'allows': 'ʓ',
    'almost': 'ԃ',
    'already': 'Ɗ',
    'alternatives': 'ݝ',
    'amiodarone': 'ࡷ',
    'among': 'í',
    'an': 'H',
    'analysis': 'Ɲ',
    'analytics': '۴',
    'and': '+',
    'announced': 'ٹ',
    'annual': '୲',
    'answer': 'ʒ',
    'anxiety': 'Î',
    'any': '5',
    'anything': 'ޅ',
    'apparently': '२',
    'application': 'ƺ',
    'apply': 'ô',
    'approach': 'ƃ',
    'appropriate': '٧',
    'approval': 'ކ',
    'approved': 'އ',
    'approximately': 'א',
    'arbitration': '૧',
    'archaeological': 'ࡲ',
    'architecture': 'ƛ',
    'are': '<',
    'argument': 'ࢀ',
    'arising': 'Ԍ',
    'around': 'ʑ',
    'artificial': 'ג',
    'as': 'Q',
    'assessment': 'ɕ',
    'assistance': 'ૠ',
    'associated': 'ɔ',
    'assumption': 'ʧ',
    'at': 'c',
    'attached': 'ފ',
    'attorney': 'ӯ',
    'attribute': 'ۄ',
    'authentication': 'Ɠ',
    'authorization': 'ܙ',
    'automated': 'ۅ',
    'automatic': 'ۆ',
    'automatically': 'ֈ',
    'available': 'ƞ',
    'average': 'ࠉ',
    'avoid': 'ࢸ',
    'back': 'È',
    'based': 'Ǥ',
    'be': 'b',
    'because': 'l',
    'been': ']',
    'before': 'e',
    'behavior': 'ʷ',
    'behind': 'ʐ',
    'believe': 'Ǎ',
    'below': 'ࠊ',
    'better': 'ʏ',
    'between': 'ƕ',
    'board': 'ઉ',
    'both': 'Ք',
    'boundaries': 'ב',
    'breach': 'ބ',
    'browser': 'Ȭ',
    'building': 'Փ',
    'built': 'ਛ',
    'business': 'ʶ',
    'businesses': 'ବ',
    'but': '9',
    'by': 'L',
    'calendar': 'כ',
    'can': '|',
    'cancellation': 'ԛ',
    'capacity': 'ʵ',
    'cardiovascular': 'ࡺ',
    'categories': 'ڶ',
    'center': 'ř',
    'certificate': 'ė',
    'chain': 'ԭ',
    'change': 'ð',
    'changed': 'Ӎ',
    'changes': 'ǃ',
    'charging': 'ಀ',
    'class': 'ӏ',
    'clause': 'Ծ',
    'clinical': 'Ӈ',
    'code': 'Ֆ',
    'coffee': 'ǌ',
    'collaboration': 'Ϧ',
    'collection': 'ڵ',
    'combination': '٣',
    'commercial': 'ॽ',
    'commission': 'ơ',
    'commitment': 'Ԩ',
    'committee': 'ۏ',
    'communication': 'Ӭ',
    'company': 'ē',
    "company's": 'छ',
    'compared': 'ޗ',
    'compatibility': 'ǵ',
    'compelling': 'ւ',
    'compensation': '੩',
    'competitive': 'ࠐ',
    'complete': 'ޘ',
    'completely': 'ƙ',
    'completing': 'ʇ',
    'complex': 'ʌ',
    'complexity': 'ڲ',
    'compliance': 'ଔ',
    'complimentary': 'ք',
    'component': 'ō',
    'compost': 'प',
    'compressions': 'ɸ',
    'computational': 'ƫ',
    'concentrations': 'ӳ',
    'conditions': 'Ƴ',
    'conference': 'શ',
    'configuration': 'Ƙ',
    'configure': 'ɰ',
    'configured': 'ڱ',
    'confirm': 'ӌ',
    'congestion': 'ഐ',
    'connection': 'ڰ',
    'connections': 'Ϫ',
    'consecutive': 'ڴ',
    'consider': 'ǖ',
    'consistent': 'گ',
    'consistently': 'צ',
    'construction': 'ɝ',
    'consumer': 'ݺ',
    'consumers': 'ٴ',
    'consumption': 'ಠ',
    'containing': 'Ӻ',
    'content': 'ĵ',
    'continuous': 'ژ',
    'contract': 'ޜ',
    'contractual': 'ಢ',
    'control': 'ą',
    'controlling': 'Ӑ',
    'conventional': 'ɿ',
    'conversation': 'פ',
    'cooperative': 'Ԗ',
    'correctly': 'ƶ',
    'correlation': 'Շ',
    'cost': 'ǽ',
    'costs': 'ə',
    'could': 'ǎ',
    'count': 'ਓ',
    'countries': 'ń',
    'create': 'ò',
    'created': 'թ',
    'creating': 'ޠ',
    'credentials': 'Ƹ',
    'critical': 'ɡ',
    'current': 'Ɖ',
    'currently': 'ǳ',
    'custom': 'ț',
    'customer': 'ǆ',
    'customers': 'ɲ',
    'daily': 'Ɇ',
    'dashboard': 'Ƶ',
    'data': 'F',
    'database': 'ޣ',
    'databases': 'ۮ',
    'dataset': 'ø',
    'day': 'Ô',
    'days': 'Ց',
    'debugging': 'ۯ',
    'decision': 'ʮ',
    'deduplication': 'ڌ',
    'default': 'ӈ',
    'degradation': 'Ԑ',
    'deletion': 'җ',
    'delivery': 'ޥ',
    'demonstrate': 'ي',
    'demonstrated': '३',
    'demonstrates': 'Ǐ',
    'density': 'ࣉ',
    'department': 'ڪ',
    'dependencies': 'ȷ',
    'depending': '۲',
    'deployment': 'Ʀ',
    'design': 'ö',
    'details': 'ķ',
    'development': 'Ⱦ',
    'diagnosis': 'ی',
    'dietary': 'অ',
    'difference': 'ڨ',
    'different': 'Ɓ',
    'dimensions': 'ಮ',
    'direct': '೧',
    'direction': 'ɯ',
    'directly': '߄',
    'disaster': 'ҟ',
    'disclaimer': 'ԝ',
    'disclosure': 'ʹ',
    'discovered': 'ࠨ',
    'discrepancy': 'ȍ',
    'discussed': 'ɮ',
    'discussion': 'ԣ',
    'discussions': 'Ƚ',
    'disproportionately': 'Ղ',
    'distinction': 'ײ',
    'distributed': 'ڹ',
    'distributes': 'ਊ',
    'district': 'ח',
    'document': 'ʭ',
    'documented': 'ୟ',
    'documents': '۷',
    "doesn't": 'ࡐ',
    'dollars': '੪',
    "don't": 'ǻ',
    'down': 'Ϲ',
    'downtown': 'ӎ',
    'duplicate': 'ň',
    'duration': '߉',
    'during': 'Ƭ',
    'each': 'w',
    'early': 'ĭ',
    'education': '۸',
    'effect': 'ܛ',
    'effective': 'ɭ',
    'effects': 'ݭ',
    'efficiency': 'ೲ',
    'efficient': '۹',
    'eight': 'જ',
    'eighteen': 'ߋ',
    'eighty': 'ॺ',
    'either': 'ॻ',
    'elasticity': 'ࡻ',
    'electrocardiogram': 'ɚ',
    'elevated': 'ન',
    'embeddings': 'ï',
    'emergency': 'ۻ',
    'emissions': 'ې',
    'employee': 'ઽ',
    'employees': 'Ϣ',
    'employment': 'Ǵ',
    'encryption': 'ڤ',
    'endpoint': 'ݟ',
    'endpoints': 'ڃ',
    'energy': 'ŝ',
    'enforcement': 'ر',
    'engineering': 'ق',
    'enough': 'ѻ',
    'enterprise': 'ܪ',
    'entirely': 'ן',
    'environment': 'Ơ',
    'error': 'Ȇ',
    'establish': 'ۼ',
    'estimated': 'ӡ',
    'evaluating': 'Ȍ',
    'even': 'ʃ',
    'evening': 'ŕ',
    'event': 'ԧ',
    'events': 'ӷ',
    'every': 'ǀ',
    'everyone': 'Ș',
    "everyone's": 'ԯ',
    'everything': 'ɏ',
    'evidence': 'ߚ',
    'exceeded': 'ߛ',
    'exceeding': 'ۉ',
    'execution': 'ܐ',
    'existing': 'ߜ',
    'expansion': 'ܒ',
    'expected': 'ସ',
    'experience': 'ƥ',
    'experiencing': 'ˡ',
    'experiment': 'ü',
    'explicitly': 'ߟ',
    'exposure': 'ঢ়',
    'expressions': 'ࠎ',
    'extension': 'ٯ',
    'facilities': 'ݔ',
    'fails': 'ষ',
    'failure': 'ۊ',
    'failures': 'ߡ',
    'faster': '߇',
    'father': 'ঐ',
    'faucet': 'ȿ',
    'features': 'ȗ',
    'fifteen': 'ࡠ',
    'fifty': 'ઢ',
    'file': 'Ə',
    'filter': 'ঊ',
    'finally': 'Ȫ',
    'find': 'á',
    'findings': 'ʬ',
    'first': 'A',
    'five': 'ǡ',
    'floor': 'च',
    'follow': 'é',
    'following': 'ɫ',
    'for': '@',
    'forty': 'Ԥ',
    'forward': 'ӆ',
    'foundation': 'ڡ',
    'four': 'ˉ',
    'fourteen': 'ã',
    'framework': 'ƴ',
    'from': '%',
    'frustration': 'ת',
    'full': 'ϥ',
    'funding': 'ࡨ',
    'funds': 'ਫ',
    'general': 'Ǝ',
    'generate': 'ę',
    'generation': 'ڠ',
    'gently': 'ক',
    'geographic': 'ɼ',
    'gigabyte': 'Հ',
    'gigabytes': 'त',
    'good': 'Ͻ',
    'gradually': 'ǰ',
    'grandfather': 'ĉ',
    'group': 'Ú',
    'growth': 'š',
    'had': 'ȴ',
    'handle': 'ÿ',
    'happened': '౹',
    'happening': 'ʉ',
    'harder': 'य़',
    'has': '_',
    'have': '[',
    'header': 'ɷ',
    'health': 'œ',
    'here': 'ˈ',
    'hierarchical': 'נ',
    'higher': 'ɧ',
    'his': 'ϫ',
    'historical': 'Ʃ',
    'history': 'ӂ',
    'home': 'Չ',
    'hours': 'ɻ',
    'how': 'v',
    'hundred': 'Ȩ',
    'hypertension': 'ॾ',
    'hypothesis': 'Ǉ',
    "i've": 'q',
    'identified': 'ܧ',
    'identifier': 'ڝ',
    'identifies': 'Ն',
    'if': '6',
    'imaging': 'ʝ',
    'immediately': 'ؽ',
    'implement': 'ܞ',
    'implemented': 'ԍ',
    'implementing': 'ȶ',
    'improvement': 'Ɵ',
    'improvements': '٢',
    'improves': 'Ç',
    'improving': 'ܠ',
    'in': 'Z',
    'include': 'Ɩ',
    'included': 'Â',
    'includes': '౽',
    'including': 'ɪ',
    'inconsistent': 'Ԯ',
    'increase': 'ċ',
    'increased': 'Ӧ',
    'increasing': 'Ɍ',
    'incremental': 'ػ',
    'independently': 'ǲ',
    'indicates': 'ɩ',
    'individual': 'Ɋ',
    'individuals': 'ૐ',
    'industrial': 'എ',
    'industries': 'ދ',
    'industry': 'ݙ',
    'information': 'ƒ',
    'infrastructure': 'խ',
    'infringement': 'ɽ',
    'initialize': 'ഔ',
    'initiating': 'ڟ',
    'inspection': '૨',
    'instead': 'Ӏ',
    'institutional': 'ړ',
    'institutions': 'س',
    'instructions': 'ם',
    'instrument': 'ɐ',
    'insurance': 'ܥ',
    'integration': 'ظ',
    'intellectual': 'ડ',
    'interest': 'ಒ',
    'interesting': 'Ւ',
    'intermediate': 'ঈ',
    'intermittent': 'ɾ',
    'internal': 'æ',
    'international': '૪',
    'interval': 'ಌ',
    'interventions': 'ڋ',
    'into': 'В',
    'introducing': 'Ǫ',
    'introduction': 'ˣ',
    'investigation': 'ջ',
    'investment': 'ࡼ',
    'invitation': 'ղ',
    'is': '$',
    "isn't": 'ԟ',
    'issue': 'ĺ',
    'it': '7',
    "it's": 'h',
    'its': 'ӊ',
    'itself': 'ট',
    'jurisdiction': 'ଛ',
    'jurisdictions': 'ଊ',
    'just': 'S',
    'keep': 'ê',
    'kitchen': 'ࢄ',
    'know': 'O',
    'language': 'Ǔ',
    'languages': 'Ǚ',
    'largest': 'Ӣ',
    'last': 'Ǘ',
    'latency': 'ҥ',
    'leadership': 'ږ',
    'learning': 'ƿ',
    'least': 'ૡ',
    'less': 'ʽ',
    'let': 'u',
    'level': 'ŷ',
    'levels': 'ӭ',
    'liability': 'ӗ',
    'library': 'Ï',
    'lifestyle': 'Ԃ',
    'like': '4',
    'limitation': 'ߑ',
    'limited': 'ݹ',
    'litigation': 'ચ',
    'local': 'ଞ',
    'located': 'ǅ',
    'looking': 'ȧ',
    'machine': 'ࢍ',
    'made': 'Մ',
    'magnitude': 'ɦ',
    'maintain': 'ĩ',
    'maintained': 'ռ',
    'maintenance': 'Խ',
    'make': 'N',
    'making': 'ʎ',
    'management': 'ɉ',
    'manager': 'қ',
    'manufacturing': 'չ',
    'market': 'ǟ',
    'material': 'ݖ',
    'materials': 'ܬ',
    'matter': 'ࡱ',
    'may': 'ϱ',
    'measure': 'ʣ',
    'measurements': 'ԫ',
    'measuring': 'ࢨ',
    'mechanism': 'Ʋ',
    'mediation': 'ऴ',
    'medical': 'ੴ',
    'meeting': 'Ƣ',
    'megabytes': 'ܭ',
    'memory': 'ভ',
    'message': 'ǂ',
    'migration': 'Պ',
    'milligrams': 'Ϸ',
    'millimeters': 'ಪ',
    'million': 'ϸ',
    'milliseconds': 'ద',
    'minimum': 'फ़',
    'minute': 'ʍ',
    'minutes': 'Ɣ',
    'model': 'g',
    'moderate': 'ಇ',
    'modification': 'ݵ',
    'module': 'Ǟ',
    'monitoring': 'ڎ',
    'month': 'Þ',
    'monthly': 'ؾ',
    'months': 'Ӫ',
    'more': '`',
    'morning': 'ҙ',
    'most': 't',
    'must': 'ɒ',
    'need': 'Y',
    'needs': 'ଉ',
    'negative': 'ಖ',
    'network': 'ľ',
    'never': 'ϗ',
    'new': '2',
    'next': 'B',
    'nine': 'ձ',
    'ninety': 'ϧ',
    'nobody': 'ک',
    'not': 'Ͽ',
    'nothing': 'ɗ',
    'notice': 'ŏ',
    'notification': 'ט',
    'notifications': 'ո',
    'now': 'ʿ',
    'obligation': 'ތ',
    'obligations': '୮',
    'observation': 'ȼ',
    'observed': 'ಛ',
    'of': 'X',
    'office': 'ह',
    'officials': 'ࠃ',
    'on': 'V',
    'one': '}',
    'only': 'ʀ',
    'operations': 'Ö',
    'opportunities': 'շ',
    'or': '*',
    'order': 'ű',
    'organization': 'છ',
    'organizations': 'ڐ',
    'other': 'Ͼ',
    'otherwise': 'ݏ',
    'our': '\\',
    'out': '0',
    'outcomes': 'ర',
    'output': 'ʆ',
    'over': 'Ȃ',
    'overall': 'î',
    'override': 'ಏ',
    'parking': 'ॶ',
    'participants': 'ભ',
    'party': 'ࢳ',
    'password': 'ȑ',
    'passwords': 'ٮ',
    'patient': 'ࢯ',
    'patients': 'બ',
    'pattern': 'ৼ',
    'patterns': 'ƾ',
    'payment': 'Ҏ',
    'payments': 'Ԇ',
    'people': 'ݍ',
    'per': 'Ǡ',
    'percent': 'Ǩ',
    'percentage': 'ഗ',
    'performance': 'Ƒ',
    'period': 'ŋ',
    'permissions': 'ج',
    'persists': 'ש',
    'personal': 'ϛ',
    'phase': 'ԕ',
    'physical': 'ɍ',
    'place': 'Ë',
    'plan': 'ϡ',
    'planning': 'ತ',
    'platform': 'ʂ',
    'please': 'ƅ',
    'point': 'Ù',
    'points': 'ஓ',
    'polarization': 'Ԝ',
    'policy': 'ŗ',
    'portfolio': 'ࢾ',
    'position': 'ě',
    'positioning': 'Ӆ',
    'positions': 'ݒ',
    'positive': 'ʦ',
    'potential': 'ǯ',
    'practical': 'ݓ',
    'practices': 'ल',
    'preferences': 'ڷ',
    'premium': 'ҍ',
    'prescribed': 'व',
    'present': 'ǧ',
    'presentation': 'Ƿ',
    'presenting': 'ࡥ',
    'pressed': 'Ҍ',
    'pressure': 'ݰ',
    'prevent': 'ɜ',
    'previous': 'Ռ',
    'pricing': 'ҋ',
    'primary': 'Ȥ',
    'prioritize': 'ڄ',
    'problem': 'Ʒ',
    'process': 'ď',
    'processed': 'ɤ',
    'processing': 'Ƥ',
    'produce': 'ࢷ',
    'product': 'ҁ',
    'production': 'Ǜ',
    'professional': 'Ԟ',
    'project': 'ĕ',
    'projects': 'ಫ',
    'proper': 'ޖ',
    'properly': 'Ǒ',
    'property': 'ä',
    'propose': 'ȣ',
    'protection': 'ఢ',
    'provided': 'Ӳ',
    'public': 'ֆ',
    'purchase': 'ׯ',
    'purpose': 'ĝ',
    'quality': 'Ȣ',
    'quarter': 'Ҁ',
    'quarterly': 'ɢ',
    'queries': 'ࢺ',
    'question': 'ʤ',
    'rate': 'p',
    'rates': 'ǚ',
    'rather': 'ǝ',
    'reaching': 'ವ',
    'readable': 'ϯ',
    'reading': 'গ',
    'real': 'ϟ',
    'reasonable': 'ڗ',
    'rebuild': 'ध',
    'receive': 'ॱ',
    'receiving': '੬',
    'recommend': 'Ǯ',
    'recommended': 'ȸ',
    'record': 'ũ',
    'recovery': 'ˁ',
    'reduced': 'ࢿ',
    'reducing': '৶',
    'reduction': 'ǭ',
    'reductions': 'ࡪ',
    'reference': 'ɠ',
    'regardless': 'ܨ',
    'regional': 'ఌ',
    'regular': 'Ǌ',
    'regulation': 'ʰ',
    'regulations': 's',
    'regulatory': 'Ʌ',
    'related': 'ࣃ',
    'relationship': 'ה',
    'release': 'Ѿ',
    'reliability': 'Ÿ',
    'remaining': '۰',
    'remains': 'ѽ',
    'remediation': 'ದ',
    'remembered': 'ࠄ',
    'remote': 'ଭ',
    'remove': 'ó',
    'removeeventlistener': 'ಭ',
    'renewal': 'ȡ',
    'replacement': 'ا',
    'report': 'ʋ',
    'reported': 'ɛ',
    'reporting': 'ɟ',
    'request': 'ŀ',
    'requested': 'ݠ',
    'requests': 'ʗ',
    'require': 'û',
    'required': 'ೞ',
    'requirements': 'ư',
    'requires': '੮',
    'requiring': 'ݡ',
    'research': 'ƽ',
    'residential': 'Ը',
    'resolution': 'Ʉ',
    'resolved': 'ڙ',
    'resource': 'ȏ',
    'resources': 'ɞ',
    'respiratory': 'ಈ',
    'response': 'į',
    'restrictions': 'ف',
    'results': 'ǁ',
    'retaliation': 'ǩ',
    'retention': 'ݢ',
    'returns': 'Ԭ',
    'revealed': 'ע',
    'reveals': 'Ŷ',
    'revenue': 'ࣈ',
    'review': 'ő',
    'reviews': 'ʔ',
    'right': 'J',
    'rights': 'ष',
    'risk': 'Ϟ',
    'rollout': 'ઓ',
    'running': 'ȟ',
    'same': 'Լ',
    'satisfaction': 'غ',
    'saturday': 'ȹ',
    'scheduled': 'Ǭ',
    'scheduling': 'Ϩ',
    'science': 'ढ',
    'scoring': 'ɶ',
    'screening': '୦',
    'screw': 'ԙ',
    'search': 'ਕ',
    'season': 'ƚ',
    'second': 'Ȉ',
    'seconds': 'उ',
    'section': 'ˆ',
    'securities': 'ñ',
    'security': 'ʖ',
    'segment': 'Ӛ',
    'sending': 'ۀ',
    'separate': '೬',
    'server': 'ӣ',
    'service': 'đ',
    'services': 'ǐ',
    'session': 'ऌ',
    'settings': 'Ʈ',
    'seven': 'ϖ',
    'seventy': 'ଣ',
    'several': 'Ѽ',
    'severe': 'খ',
    'she': 'ʄ',
    'should': 'z',
    "shouldn't": 'ࢵ',
    'show': 'ç',
    'side': 'Å',
    'significant': 'Ɛ',
    'significantly': 'մ',
    'single': 'Ӡ',
    'six': 'Ü',
    'sixteen': 'ȉ',
    'sixty': 'ମ',
    'size': 'Ի',
    'small': 'Ԏ',
    'so': 'U',
    'social': 'r',
    'software': 'ೱ',
    'some': 'Ժ',
    'something': 'y',
    'sometimes': 'ݬ',
    'specific': 'Ɯ',
    'specification': 'ڍ',
    'specified': 'ஏ',
    'standard': 'ഇ',
    'start': 'ë',
    'started': 'Ȟ',
    'starting': 'ʜ',
    'state': 'ϔ',
    'statistics': 'ޚ',
    'status': 'ņ',
    'still': 'ƍ',
    'stone': 'ӝ',
    'storage': 'ѹ',
    'stories': 'ۑ',
    'straightforward': 'դ',
    'strategy': 'Ƽ',
    'strongest': 'ݲ',
    'structural': 'ಷ',
    'structure': 'ڻ',
    'structured': 'Ѹ',
    'structures': 'ܫ',
    'subject': 'ݕ',
    'subscription': 'Ƕ',
    'suggest': 'ȝ',
    'suggesting': 'Ж',
    'suggests': 'ì',
    'supervised': 'վ',
    'support': 'þ',
    'supports': 'Ȏ',
    'surface': 'ѷ',
    'switching': 'Í',
    'symptoms': 'ݛ',
    'system': 'k',
    'systems': 'Ȝ',
    'talking': 'ˍ',
    'target': 'ڽ',
    'team': 'o',
    'technologies': 'ع',
    'technology': 'ٸ',
    'temperature': 'ϰ',
    'temperatures': 'P',
    'ten': 'Ձ',
    'termination': 'Ϯ',
    'terms': 'Ԋ',
    'tested': 'ਬ',
    'testing': 'ɳ',
    'than': 'ȁ',
    'that': '~',
    "that's": 'ਭ',
    'the': '^',
    'their': 'D',
    'them': 'K',
    'then': 'Ǽ',
    'therapeutic': 'Ȼ',
    'therapy': 'स',
    'there': 'E',
    "there's": 'Ѷ',
    'these': 'ˠ',
    'they': 'n',
    "they're": 'झ',
    'thing': 'Ý',
    'think': 'ƌ',
    'thinking': 'ƻ',
    'third': 'ୡ',
    'thirty': 'Ӝ',
    'this': '!',
    'those': 'ɵ',
    'though': 'ӛ',
    'thought': 'à',
    'thousand': 'ʛ',
    'three': 'm',
    'through': 'f',
    'time': '3',
    'timeline': 'ǿ',
    'times': 'ˑ',
    'to': 'W',
    'total': 'Ź',
    'totaling': 'ԅ',
    'traffic': 'Ѵ',
    'training': 'ƭ',
    'transaction': 'ɖ',
    'transition': 'ٵ',
    'transitioning': 'ȃ',
    'treatment': 'É',
    'trial': 'ק',
    'trying': 'ۃ',
    'twelve': 'Ӗ',
    'twenty': 'ʈ',
    'two': 'x',
    'typically': 'ݸ',
    'under': 'Ø',
    'understand': 'Ɂ',
    'unsupervised': 'ŵ',
    'until': 'ɴ',
    'up': 'G',
    'upcoming': 'Ǿ',
    'update': 'ʅ',
    'updated': 'Ǧ',
    'updates': 'ĸ',
    'use': 'Ϻ',
    'used': 'ˀ',
    'users': 'ˏ',
    'using': 'Ǆ',
    'vaccination': 'ɓ',
    'vaccine': 'ϻ',
    'variables': 'ϳ',
    'vegetables': 'ರ',
    'verified': 'ʙ',
    'version': 'Ѱ',
    'warfarin': 'Ջ',
    'warranties': 'Ϥ',
    'was': '>',
    'watched': 'Ѯ',
    'water': 'அ',
    'way': 'R',
    'we': 'T',
    "we're": 'ԇ',
    'week': 'ß',
    'weekend': 'य',
    'weekly': 'ل',
    'weeks': 'ȯ',
    'weight': 'ਫ਼',
    'well': 'ϼ',
    'were': 'j',
    'what': '#',
    'when': 'Ȁ',
    'where': 'Ȯ',
    'whether': 'ѭ',
    'which': 'А',
    'while': 'Ƌ',
    'whistleblower': 'ࢢ',
    'who': 'Û',
    'will': 'd',
    'window': 'ǜ',
    'with': '&',
    'within': 'ȇ',
    'without': 'Ɨ',
    'work': 'M',
    'workers': '୬',
    'workflows': 'எ',
    'working': 'Ț',
    'would': '{',
    'year': 'Ѝ',
    'years': 'ˎ',
    'yesterday': 'ɘ',
    'you': ';',
    "you'll": '੨',
    "you're": 'ǹ',
    'your': 'C',
    'yourself': 'ત',
    'zero': 'ˢ',
}

# PHRASE CODEBOOK

PHRASE_CODEBOOK = {
    'thank you': 'β',
    'let me know': 'ι',
    'such as': 'τ',
    'due to': 'υ',
    'in addition to': 'χ',
    'at least': 'Β',
    'right now': 'Δ',
    'kind of': 'Ζ',
    'up to': 'Ι',
    'out of': 'Κ',
    'based on': 'Π',
    'according to': 'Σ',
    'the fact that': 'Χ',
    'in addition': 'Ψ',
    'as well': 'Ω',
    'there are': 'ѐ',
    'would be': 'Г',
    'could be': 'Д',
    'should be': 'Е',
    'has been': 'ҿ',
    'have been': 'З',
    'will be': 'И',
    'going to': 'њ',
    'able to': 'К',
    'need to': 'ѓ',
    'want to': 'М',
    'have to': 'Н',
    'used to': 'О',
    'try to': 'П',
    'seem to': 'Р',
    'language model': 'У',
    'machine learning': 'Х',
    'would like to': 'ҽ',
    'make sure': 'Ҝ',
    'we should also': 'Њ',
    'set up': 'Қ',
    'figure out': 'Ҟ',
    'think about': 'Ң',
    'it can': 'Ҥ',
    'and the': 'Ҧ',
    'to the': 'ҧ',
    'in the': 'Ҩ',
    'of the': 'ҩ',
    'with the': 'Ҫ',
    'that the': 'ҫ',
    'for the': 'Ҭ',
    'on the': 'ҭ',
    'through the': 'Ү',
    'i wanted to': 'ү',
    'by the': 'Ұ',
    'the new': 'ұ',
    'from the': 'Ҳ',
    'about the': 'ҳ',
    'the model': 'Ҵ',
    'the current': 'ҵ',
    'for your': 'Ҷ',
    'on your': 'ҷ',
    'there are a few': 'Ҹ',
    'by the end of': 'Һ',
    'the next': 'Ҿ',
    'thank you for': 'Ā',
    'the first': 'Ă',
    'wanted to': 'Ą',
    'you for your': 'ѕ',
    'let me': 'Ć',
    'by the end of this': 'ї',
    'within the next two weeks': 'Ĉ',
    'at the': 'ј',
    'like to': 'Ċ',
    'with a': 'љ',
    'all the': 'Č',
    'the system': 'Ď',
    'me know': 'ћ',
    'we need': 'Đ',
    'you through the': 'ў',
    'want to make': 'Ĕ',
    'in the next': 'ғ',
    'thank you for your': 'ˤ',
    'within the next': 'ˮ',
    'the end of this': 'Ͱ',
    'to inform you that': 'ͳ',
    'by the end of this week': 'ʹ',
    'thinking about': 'Ĝ',
    "i've been": 'Ġ',
    'the project': 'Ģ',
    'the problem': 'Ĥ',
    'your account': 'Ħ',
    'the application': 'Ĩ',
    "i've been thinking": 'İ',
    'to make sure': 'Ĵ',
    'i can': 'Ķ',
    'and i': 'Ĺ',
    'would like': 'Ļ',
    'is that': 'Ł',
    'within the': 'Ń',
    'to discuss': 'Ņ',
    'the upcoming': 'Ŋ',
    'we should': 'Œ',
    'i have': 'Ŕ',
    'we need to': 'Ř',
    'for the upcoming': 'Ŧ',
    'i wanted': 'Ũ',
    'the processing': 'Ū',
    'i appreciate': 'Ů',
    'if you': 'À',
    'you have': 'Á',
    'the most': 'Ò',
    'you through': 'Ó',
    'to maintain': 'ź',
    'rather than': 'ż',
    'one hundred': 'Ž',
    'we believe': 'ƀ',
    'the second': 'Ƃ',
    'during the': 'Ƈ',
    'before the': 'ƈ',
    'where you': 'ǉ',
    'using the': 'Ǹ',
    'two weeks': 'Ǻ',
    'this week': 'Ȱ',
    'there was': 'ȱ',
    'real time': 'ɹ',
    'last week': 'Ͷ',
    'know what': 'ͷ',
    'follow up': 'ͺ',
    'allow the': 'ͼ',
    'been thinking about': 'Ά',
    "i've been thinking about": 'Ή',
    'that the product': 'Ώ',
    'there are a': 'ΐ',
    'end of this': 'Ϊ',
    'one hundred and': 'ή',
    'navigate to the': 'ί',
    'inform you that': 'ρ',
    'within the next two': 'ς',
    'inform you that the': 'σ',
    'the next two weeks': 'ϊ',
    'want to make sure': 'ό',
    'end of this week': 'ώ',
    'the problem is': 'ϑ',
    'next two weeks': 'ϓ',
    'the implementation': 'Ю',
    'the authentication': 'а',
    'associated with': 'й',
    'twelve percent': 'л',
    'mechanism that': 'р',
    'implementing a': 'с',
    'different from': 'т',
    'the quarterly': 'х',
    'of everything': 'ш',
    'browser cache': 'ъ',
    'available for': 'ы',
    'approach that': 'ь',
    'can be': 'я',
    'you for': 'ё',
    'to make': 'ђ',
    'two thousand': 'і',
    'to configure': 'ѝ',
    'the end of': 'ѡ',
    "you'd like to": 'Ѥ',
    'are a few': 'ѧ',
    'the next two': 'ѩ',
    'of this week': 'Ѫ',
    "i'm not sure": 'ѫ',
    'the same': '¡',
    'because the': '¢',
    'when the': '£',
    'you can': '¤',
    'is the': '¥',
    'under the': '¦',
    'more than': '§',
    'than the': '¨',
    'i think': '©',
    'across the': 'ª',
    'to your': '«',
    'but the': '¬',
    'the right': '®',
    'trying to': '¯',
    'over the': '°',
    'and a': '±',
    'in a': '²',
    'if the': '³',
    'to a': '´',
    'was a': 'µ',
    'of our': '¶',
    'it was': '·',
    'from a': '¸',
    'for a': '¹',
    'the cost': 'º',
    'we have': '»',
    'do not': '¼',
    'a single': '½',
    'does not': '¾',
    'to be': '¿',
    'of a': 'Ã',
    'the best': 'Ä',
    'the end': 'Æ',
    'as a': 'Ê',
    'may be': 'Ì',
    'which is': 'Ð',
    'that you': 'Ñ',
    'into the': 'Õ',
    'after the': '×',
    'between the': 'â',
    'since the': 'è',
    'not a': 'õ',
    'i recommend': '÷',
    'the entire': 'ù',
    'that our': 'ú',
    'to our': 'ý',
    'of this': 'ā',
    'needs to': 'ă',
    'the old': 'ć',
    'so you': 'Ē',
}

# VOWEL STRIPPING PARAMETERS
MIN_VOWEL_STRIP_LENGTH = 4

VOWEL_STRIP_EXCEPTIONS = {
    'area', 'audio', 'base', 'case', 'code', 'data',
    'false', 'file', 'idea', 'image', 'meta', 'mode',
    'node', 'none', 'note', 'null', 'queue', 'quote',
    'radio', 'rate', 'ratio', 'role', 'rule', 'state',
    'table', 'true', 'type', 'value', 'video',
}

PROTECTED_SHORTHAND = {
    'admin', 'afk', 'api', 'app', 'asap', 'auth', 'brb', 'btw',
    'css', 'db', 'dev', 'diy', 'doc', 'docs', 'eta', 'faq',
    'fomo', 'ftw', 'fyi', 'gg', 'gtg', 'html', 'idk', 'imho',
    'imo', 'info', 'irl', 'jk', 'js', 'lmk', 'lol', 'msg',
    'np', 'nvm', 'omg', 'omw', 'pic', 'pls', 'rofl', 'rsvp',
    'smh', 'sql', 'tbh', 'thx', 'tldr', 'tmi', 'ttyl', 'ty',
    'ui', 'url', 'ux', 'wip', 'wtf', 'yolo',
}

MORPHOLOGICAL_PATTERNS = [
    (r'^(.+?)tion$', 'tn'),
    (r'^(.+?)sion$', 'sn'),
    (r'^(.+?)ment$', 'mt'),
    (r'^(.+?)ness$', 'ns'),
    (r'^(.+?)able$', 'bl'),
    (r'^(.+?)ible$', 'bl'),
    (r'^(.+?)ity$', 'ty'),
    (r'^(.+?)ous$', 'us'),
    (r'^(.+?)ful$', 'fl'),
    (r'^(.+?)less$', 'ls'),
    (r'^(.+?)ling$', 'lng'),
    (r'^(.+?)ting$', 'tng'),
    (r'^(.+?)ning$', 'nng'),
    (r'^(.+?)ring$', 'rng'),
    (r'^(.+?)sing$', 'sng'),
    (r'^(.+?)ing$', 'ng'),
    (r'^(.+?)ily$', 'ly'),
    (r'^(.+?)ally$', 'ly'),
    (r'^(.+?)ly$', 'ly'),
    (r'^(.+?)ed$', 'd'),
    (r'^(.+?)er$', 'r'),
    (r'^(.+?)est$', 'st'),
    (r'^(.+?)es$', 's'),
    (r'^(.+?)s$', 's'),
]

MIN_BASE_LENGTH = 3
